const columns = t => [
  {
    headerName: t('fields.companyCode'),
    field: 'report_cmpycode',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.company'),
    field: 'report_cmpyname',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
  },
  {
    headerName: t('fields.type'),
    field: 'report_type_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
  },
  {
    headerName: t('fields.name'),
    field: 'report_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.description'),
    field: 'report_desc',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.source'),
    field: 'report_jasper_file',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.email'),
    field: 'report_cmpyemail',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.enabled'),
    field: 'report_enabled',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.active'),
    field: 'report_active',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.canBePrinted'),
    field: 'report_canprint',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.canBeEmailed'),
    field: 'report_canemail',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.onDemandReport'),
    field: 'report_ondemand_flag',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.closeOutReport'),
    field: 'report_closeout_flag',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
  },
];

export default columns;
