import _ from 'lodash';

const columns = (t, reasons, config) => [
  {
    headerName: t('fields.baseOwnerTransNo'),
    field: 'ownship_trsa_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    hide: false,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransQuantity'), //+ ' (' + t('units.ltr') + ')',
    field: 'qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransUnitCode'),
    field: 'trsa_unit',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransUnit'),
    field: 'description',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransReason'),
    field: 'reason',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 200,
    suppressSizeToFit: true,
    cellRenderer: 'ListRenderer',
    cellRendererParams: {
      values: _.uniq(
        _.map(reasons, (item) => {
          return { code: item.reason_id, name: item.reason_text };
        })
      ),
    },
  },
  {
    headerName: t('fields.baseOwnerTransReason'),
    field: 'reason_text',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 200,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransDensity') + ' (' + t('units.kg/m3') + ')',
    field: 'trsa_density',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 240,
    suppressSizeToFit: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },
  {
    headerName: t('fields.baseOwnerTransTime'),
    field: 'trsa_time',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.baseOwnerNo'),
    field: 'ownship_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    hide: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransSuppCode'),
    field: 'supp_cmpy',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransSuppName'),
    field: 'cmpy_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 280,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransProdCode'),
    field: 'base_prod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerTransProdName'),
    field: 'base_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 240,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerTransProdClassDesc'),
    field: 'bclass_desc',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 240,
    suppressSizeToFit: true,
    hide: false,
  },

  {
    headerName: t('fields.baseOwnerQuantityBeforeTrans'), //+ ' (' + t('units.ltr') + ')',
    field: 'trsa_qty_owned',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 250,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerDensityBeforeTrans') + ' (' + t('units.kg/m3') + ')',
    field: 'trsa_density_owned',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 290,
    suppressSizeToFit: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },

  {
    headerName: t('fields.baseOwnerQuantityAfterTrans'), //+ ' (' + t('units.ltr') + ')',
    field: 'trsa_qty_after',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 250,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerDensityAfterTrans') + ' (' + t('units.kg/m3') + ')',
    field: 'trsa_density_after',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 290,
    suppressSizeToFit: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },

  {
    headerName: t('fields.baseOwnerQuantityCurrent'), //+ ' (' + t('units.ltr') + ')',
    field: 'ownship_qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 250,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerDensityCurrent') + ' (' + t('units.kg/m3') + ')',
    field: 'ownship_density',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 290,
    suppressSizeToFit: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },
];

export default columns;
