const columns = (t) => [
  {
    headerName: t('fields.mtDataId'),
    field: 'mt_id',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataStatus'),
    field: 'mt_status',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataUser'),
    field: 'mt_user',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataCreateDate'),
    field: 'mt_create_date',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 125,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.mtDataType'),
    field: 'mt_type',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataSupplier'),
    field: 'mt_supplier',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataCustomer'),
    field: 'mt_customer',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataTripNo'),
    field: 'mt_trip_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataOrderNo'),
    field: 'mt_order_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataCarrier'),
    field: 'mt_carrier',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataTanker'),
    field: 'mt_tanker',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataDriver'),
    field: 'mt_driver',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataTasRef'),
    field: 'mt_tas_ref',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataUserComments'),
    field: 'mt_user_comments',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.mtDataStartTime'),
    field: 'mt_datetime_st',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 125,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.mtDataEndTime'),
    field: 'mt_datetime_ed',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 125,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.mtDataUpdateDate'),
    field: 'mt_update_date',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 125,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
];

export default columns;
