const columns = (t, visible, config) => [
  {
    headerName: t('fields.terminal'),
    field: 'ownship_terminal',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.terminal'),
    field: 'bpo_sitedesc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    hide: !config?.siteUseMultiTerminals,
  },
  {
    headerName: t('fields.baseOwnerNo'),
    field: 'ownship_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    hide: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerSuppCode'),
    field: 'supp_cmpy',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerSuppName'),
    field: 'cmpy_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 280,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerProdCode'),
    field: 'base_prod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    hide: !visible,
  },
  {
    headerName: t('fields.baseOwnerProdName'),
    field: 'base_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 240,
    suppressSizeToFit: true,
    hide: !visible,
  },
  {
    headerName: t('fields.baseOwnerProdClassDesc'),
    field: 'bclass_desc',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 240,
    suppressSizeToFit: true,
    hide: !visible,
  },

  {
    headerName: t('fields.tkoPercentage'),
    field: 'bpo_percentage',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    cellRenderer: 'QuantityRenderer',
    cellRendererParams: {
      digits: '4',
      min: '0',
    },
  },
  {
    headerName: t('fields.baseOwnerQuantity'), //+ ' (' + t('units.ltr') + ')',
    field: 'ownship_qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
  },
  {
    headerName: t('fields.baseOwnerDensity') + ' (' + t('units.kg/m3') + ')',
    field: 'ownship_density',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 240,
    suppressSizeToFit: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },
  {
    headerName: t('fields.baseOwnerUnitCode'),
    field: 'ownship_unit',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerUnit'),
    field: 'description',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 200,
    suppressSizeToFit: true,
  },
];

export default columns;
