import React, { Component } from 'react';
import { Badge } from 'antd';
import './source-render.css';

export default class SourceRender extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: this.props.value,
    };
  }

  getBadge = () => {
    const { data } = this.props;
    // const code = this.state.value;
    const code = data?.shls_srctype;

    /*
      0	U	Unknown source            - Unknown
      1	M	Created manually          - Manually Created
      2	H	Received from host        - From Host
      3	O	Generated by open order   - Open Order
      4	S	Generated by system       - Standalone or Special
    */

    if (code === "1") {
      return "yellow";
    } else if (code === "2") {
      return "green";
    } else if (code === "3") {
      return "geekblue";
    } else if (code === "4") {
      return "gold";
    } else {
      return "red";
    };
  }

  render() {
    return (
      <div style={{ width: '100%',  display: 'flex' }}>
        <Badge color={this.getBadge()} text={this.state.value} />
      </div>
    );
  }
}
