import React, { Component } from 'react';
import { Badge } from 'antd';
import './source-render.css';

/*
  SHLS_SRCTYPE
  0	U	Unknown source            - Unknown
  1	M	Created manually          - Manually Created
  2	H	Received from host        - From Host
  3	O	Generated by open order   - Open Order
  4	S	Generated by system       - Standalone or Special
*/
/*
  SHLS_PICKUP_MODE
  0: Load Schedule
  1: Pickup Schedule
  2: Staged Schedule
*/

export default class SourceRender extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: this.props.value,
    };
  }

  getBadge = () => {
    const { data, flag } = this.props;
    const code = data?.shls_srctype;
    const mode = data?.shls_pickup_mode;

    if (code === '1') {
      if (flag && mode === '1') {
        return '#D7D700';
      } else {
        return 'yellow'; // #FFFF00
      }
    } else if (code === '2') {
      return 'green';
    } else if (code === '3') {
      return 'geekblue';
    } else if (code === '4') {
      if (flag && mode === '1') {
        return '#D78800';
      } else {
        return 'gold'; // #FFD700
      }
    } else {
      return 'red';
    }
  };

  getLabel = () => {
    const { data, t, flag } = this.props;
    const code = data?.shls_srctype;
    const mode = data?.shls_pickup_mode;

    if (flag && mode === '1' && (code === '1' || code === '4')) {
      return `${t('fields.stagingBayPickupLoad')}: ${this.state.value}`;
    } else {
      return this.state.value;
    }
  };

  render() {
    return (
      <div style={{ width: '100%', display: 'flex' }}>
        <Badge color={this.getBadge()} text={this.getLabel()} />
      </div>
    );
  }
}
