const columns = (t) => [
    {
      headerName: t('fields.delvCode'),
      field: 'delv_code',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 150,
      suppressSizeToFit: true,
    },
    {
      headerName: t('fields.delvName'),
      field: 'delv_name',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 200,
    },
    {
      headerName: t('fields.delvGrid'),
      field: 'delv_grid',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 80,
    },
    {
      headerName: t('fields.delvAddrCode'),
      field: 'delv_addr_code',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvAddrText'),
      field: 'delv_addr_text',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvAddrDesc'),
      field: 'delv_addr_desc',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
    },

    {
      headerName: t('fields.delvTrspTypeId'),
      field: 'delv_trsp_typeid',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvTrspTypeName'),
      field: 'delv_trsp_typename',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 100,
    },
    {
      headerName: t('fields.delvDocTypeId'),
      field: 'delv_doc_typeid',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvDocTypeName'),
      field: 'delv_doc_typename',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 100,
    },
    {
      headerName: t('fields.delvQtyTypeId'),
      field: 'delv_qty_typeid',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvQtyTypeName'),
      field: 'delv_qty_typename',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 100,
    },
    {
      headerName: t('fields.delvEtypId'),
      field: 'delv_etyp_id',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvEtypTitle'),
      field: 'delv_etyp_title',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 160,
    },
    {
      headerName: t('fields.delvTripTime'),
      field: 'delv_trip_time',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvDistance'),
      field: 'delv_distance',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvTarrif'),
      field: 'delv_tarrif',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },

    {
      headerName: t('fields.delvContact'),
      field: 'delv_contact',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvPhone'),
      field: 'delv_phone',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvPrfCode'),
      field: 'delv_prf_code',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvPrfDesc'),
      field: 'delv_prf_desc',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },

    {
      headerName: t('fields.delvCustAcct'),
      field: 'delv_cust_acct',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvCustAcctDesc'),
      field: 'delv_cust_acctdesc',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvCustCmpyCode'),
      field: 'delv_cust_cmpycode',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvCustCmpyName'),
      field: 'delv_cust_cmpyname',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvCustSuppCode'),
      field: 'delv_cust_suppcode',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvCustSuppName'),
      field: 'delv_cust_suppname',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvCustCatgCode'),
      field: 'delv_cust_catgcode',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvCustCatgText'),
      field: 'delv_cust_catgtext',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      hide: true,
    },
    {
      headerName: t('fields.delvCustCount'),
      field: 'delv_cust_count',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 110,
    },
    {
      headerName: t('fields.delvOrderCount'),
      field: 'delv_order_count',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      width: 100,
    },
  ];
  

  export default columns;
  