const columns = (t, config) => [
  {
    headerName: t('fields.baseProductCode'),
    field: 'pitem_base_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 140,
    pinned: "left",
  },
  {
    headerName: t('fields.baseProductName'),
    field: 'pitem_base_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 180,
    pinned: "left",
  },
  {
    headerName: t('fields.ratio'),
    field: 'pitem_ratio_value',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 80,
  },
  {
    headerName: t('fields.blendToleranceCheck'),
    field: 'pitem_bltol_flag',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    cellRenderer: 'BooleanRenderer',
    width: 180,
  },
  {
    headerName: t('fields.lowerLimit'),
    field: 'pitem_bltol_ntol',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 130,
  },
  {
    headerName: t('fields.upperLimit'),
    field: 'pitem_bltol_ptol',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 130,
  },
  {
    headerName: t('fields.baseClass'),
    field: 'pitem_bclass_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 130,
  },
  {
    headerName: t('fields.checkHotLitre'),
    field: 'pitem_hot_check',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true, 
    hide: !config.manageHotProduct,
    width: 150,
  },
];

export default columns;
