<?php

include_once __DIR__ . '/../shared/journal.php';
include_once __DIR__ . '/../shared/log.php';
include_once 'common_class.php';

class SiteBal extends CommonClass
{
    protected $TABLE_NAME = 'TANKS';

    public function read()
    {
        $query = "
        SELECT
        TANKS.TANK_CODE TANKCODE,
        BASE_PRODS.BASE_CODE PRODUCTCODE,
        BASE_PRODS.BASE_NAME PRODUCTNAME,
        NVL(TANKS.TANK_DENSITY, 0.0) TANK_DENSITY,
        NVL(TANKS.TANK_LTR_CLOSE, 0.0)*NVL(TANKS.TANK_RPTVCFCLOSE, 1) OPENINGSTOCK,
        NVL(TANKS.TANK_LTR_CLOSE, 0.0)*NVL(TANKS.TANK_RPTVCFCLOSE, 1) + NVL(TANK_RCPT_VOL, 0.0)*NVL(TANKS.TANK_RPTVCF, 1) ACCNTTOT,
        NVL(TANKS.TANK_TRF_VOL, 0.0)*NVL(TANKS.TANK_RPTVCF, 1) TRANSFERVOL,
        NVL(TANKS.TANK_LTR_CLOSE, 0.0)*NVL(TANKS.TANK_RPTVCFCLOSE, 1) + NVL(TANKS.TANK_RCPT_VOL, 0.0)*NVL(TANKS.TANK_RPTVCF, 1) - NVL(TANKS.TANK_TRF_VOL, 0.0) * NVL(TANKS.TANK_RPTVCF, 1) BOOKBALANCE,
        NVL(TANKS.TANK_COR_VOL, 0.0)*NVL(TANKS.TANK_RPTVCF, 1) CLOSINGSTOCK,
                    
        NVL(RCPT_CVL, 0) + NVL(TANKS.TANK_RCPT_VOL, 0.0)*NVL(TANKS.TANK_RPTVCF, 1) RECEIPTSVOL,
        NVL(TRSF_IN_CVL, 0) TRANSFERIN,
        NVL(TRSF_OUT_CVL, 0) TRANSFEROUT,
        NVL(TANKS.TANK_COR_VOL, 0.0)*NVL(TANKS.TANK_RPTVCF, 1) - NVL(TANKS.TANK_LTR_CLOSE, 0.0)*NVL(TANKS.TANK_RPTVCFCLOSE, 1) - NVL(TANKS.TANK_RCPT_VOL, 0.0) * NVL(TANKS.TANK_RPTVCF, 1)
        + NVL(TANKS.TANK_TRF_VOL, 0.0)*NVL(TANKS.TANK_RPTVCF, 1) GAINLOSS
    
    FROM TERMINAL, CLOSEOUTS, CLOSEOUT_TANK, TANKS, BASE_PRODS,
        (SELECT SUM(TRANBASE.TRSB_AVL) RCPT_AVL, SUM(TRANBASE.TRSB_CVL) RCPT_CVL, TRANBASE.TRSB_TK_TANKCODE
        FROM TRANSFERS, TRANSACTIONS, TRANBASE
        WHERE TRANBASE.TRSB_ID_TRSF_ID = TRANSFERS.TRSF_ID
            AND TRANSFERS.TRSFTRID_TRSA_ID = TRANSACTIONS.TRSA_ID
            AND TRANSACTIONS.TRSA_IOTYPE = -1
            AND TRANSACTIONS.TRSA_ED_DMY < (SELECT CLOSEOUT_DATE FROM CLOSEOUTS WHERE CLOSEOUT_NR = :cls_out)
            AND TRANSACTIONS.TRSA_ED_DMY > (SELECT PREV_CLOSEOUT_DATE FROM CLOSEOUTS WHERE CLOSEOUT_NR = :cls_out)
            AND TRANSFERS.TRSF_ID NOT IN (SELECT MTITM_TRSF_ID FROM MOV_TRSF_ITEMS, MOVEMENT_ITEMS
                WHERE MTITM_MOV_ID = MVITM_MOVE_ID AND MTITM_MOV_LINE = MVITM_LINE_ID AND MVITM_TYPE = 2)
        GROUP BY TRANBASE.TRSB_TK_TANKCODE) RECEIPT_INFO,
        (SELECT SUM(TRANBASE.TRSB_AVL) TRSF_IN_AVL, SUM(TRANBASE.TRSB_CVL) TRSF_IN_CVL, TRANBASE.TRSB_TK_TANKCODE
        FROM TRANSFERS, TRANSACTIONS, TRANBASE
        WHERE TRANBASE.TRSB_ID_TRSF_ID = TRANSFERS.TRSF_ID
            AND TRANSFERS.TRSFTRID_TRSA_ID = TRANSACTIONS.TRSA_ID
            AND TRANSACTIONS.TRSA_IOTYPE = -1 AND TRANSACTIONS.TRSA_CLASS = 1
            AND TRANSACTIONS.TRSA_ED_DMY < (SELECT CLOSEOUT_DATE FROM CLOSEOUTS WHERE CLOSEOUT_NR = :cls_out)
            AND TRANSACTIONS.TRSA_ED_DMY > (SELECT PREV_CLOSEOUT_DATE FROM CLOSEOUTS WHERE CLOSEOUT_NR = :cls_out)
            AND TRANSFERS.TRSF_ID IN (SELECT MTITM_TRSF_ID FROM MOV_TRSF_ITEMS, MOVEMENT_ITEMS
                WHERE MTITM_MOV_ID = MVITM_MOVE_ID AND MTITM_MOV_LINE = MVITM_LINE_ID AND MVITM_TYPE = 2)
        GROUP BY TRANBASE.TRSB_TK_TANKCODE) TRANSFER_IN_INFO,
        (SELECT SUM(TRANBASE.TRSB_AVL) TRSF_OUT_AVL, SUM(TRANBASE.TRSB_CVL) TRSF_OUT_CVL, TRANBASE.TRSB_TK_TANKCODE
        FROM TRANSFERS, TRANSACTIONS, TRANBASE
        WHERE TRANBASE.TRSB_ID_TRSF_ID = TRANSFERS.TRSF_ID
            AND TRANSFERS.TRSFTRID_TRSA_ID = TRANSACTIONS.TRSA_ID
            AND TRANSACTIONS.TRSA_IOTYPE = 1 AND TRANSACTIONS.TRSA_CLASS = 1
            AND TRANSACTIONS.TRSA_ED_DMY < (SELECT CLOSEOUT_DATE FROM CLOSEOUTS WHERE CLOSEOUT_NR = :cls_out)
            AND TRANSACTIONS.TRSA_ED_DMY > (SELECT PREV_CLOSEOUT_DATE FROM CLOSEOUTS WHERE CLOSEOUT_NR = :cls_out)
        GROUP BY TRANBASE.TRSB_TK_TANKCODE) TRANSFER_OUT_INFO,
        (SELECT SUM(TRANBASE.TRSB_AVL) RACK_AVL, SUM(TRANBASE.TRSB_CVL) RACK_CVL, TRANBASE.TRSB_TK_TANKCODE
        FROM TRANSFERS, TRANSACTIONS, TRANBASE
        WHERE TRANBASE.TRSB_ID_TRSF_ID = TRANSFERS.TRSF_ID
            AND TRANSFERS.TRSFTRID_TRSA_ID = TRANSACTIONS.TRSA_ID
            AND TRANSACTIONS.TRSA_IOTYPE = 1 AND TRANSACTIONS.TRSA_CLASS = 0
            AND TRANSACTIONS.TRSA_ED_DMY < (SELECT CLOSEOUT_DATE FROM CLOSEOUTS WHERE CLOSEOUT_NR = :cls_out)
            AND TRANSACTIONS.TRSA_ED_DMY > (SELECT PREV_CLOSEOUT_DATE FROM CLOSEOUTS WHERE CLOSEOUT_NR = :cls_out)
            AND TRANSFERS.TRSF_ID NOT IN (SELECT MTITM_TRSF_ID FROM MOV_TRSF_ITEMS, MOVEMENT_ITEMS
                WHERE MTITM_MOV_ID = MVITM_MOVE_ID AND MTITM_MOV_LINE = MVITM_LINE_ID AND MVITM_TYPE = 2)
        GROUP BY TRANBASE.TRSB_TK_TANKCODE) RACK_INFO
    WHERE CLOSEOUTS.CLOSEOUT_NR = :cls_out
        AND CLOSEOUTS.CLOSEOUT_NR = CLOSEOUT_TANK.CLOSEOUT_NR
        AND CLOSEOUT_TANK.TANK_CODE = TANKS.TANK_CODE
        AND BASE_PRODS.BASE_CODE = TANK_BASE
        AND TANKS.TANK_CODE = RECEIPT_INFO.TRSB_TK_TANKCODE(+)
        AND TANKS.TANK_CODE = TRANSFER_IN_INFO.TRSB_TK_TANKCODE(+)
        AND TANKS.TANK_CODE = TRANSFER_OUT_INFO.TRSB_TK_TANKCODE(+)
        AND TANKS.TANK_CODE = RACK_INFO.TRSB_TK_TANKCODE(+)
    ORDER BY TANKS.TANK_CODE
    ";
        $stmt = oci_parse($this->conn, $query);
        oci_bind_by_name($stmt, ':cls_out', $this->cls_out);
        if (oci_execute($stmt, $this->commit_mode)) {
            return $stmt;
        } else {
            $e = oci_error($stmt);
            write_log("DB error:" . $e['message'], __FILE__, __LINE__, LogLevel::ERROR);
            return null;
        }
    }

    public function get_closeoutNR()
    {
        $query = "
            SELECT CLOSEOUT_NR FROM CLOSEOUTS WHERE ROWNUM <= 1 ORDER BY CLOSEOUT_NR DESC 
        ";
            $stmt = oci_parse($this->conn, $query);
        if (oci_execute($stmt, $this->commit_mode)) {
            return $stmt;
        } else {
            $e = oci_error($stmt);
            write_log("DB error:" . $e['message'], __FILE__, __LINE__, LogLevel::ERROR);
            return null;
        }
    }
}
