const columns = (t, pageState, form, arm) => [
  {
    headerName: t('fields.nomtranBaseGui'),
    field: 'trsb_bs',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
  {
    headerName: t('fields.nomtranMeterCode'),
    field: 'trsb_meter',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
  {
    headerName: t('fields.openingAmbient'),
    field: 'trsf_opn_amb',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: pageState === 'disposal' && !!arm ? true : false,

    cellClass: pageState === 'disposal' && !!arm ? 'editable-ag-grid-cell' : '',
  },
  {
    headerName: t('fields.closingAmbient'),
    field: 'trsf_cls_amb',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: pageState === 'disposal' && !!arm ? true : false,
    cellClass: pageState === 'disposal' && !!arm ? 'editable-ag-grid-cell' : '',
  },
  {
    headerName: t('fields.observedQuantity'),
    field: 'trsf_qty_amb',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
  {
    headerName: t('fields.openingCorrected'),
    field: 'trsf_opn_cor',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: pageState === 'disposal' && !!arm ? true : false,
    cellClass: pageState === 'disposal' && !!arm ? 'editable-ag-grid-cell' : '',
  },
  {
    headerName: t('fields.closingCorrected'),
    field: 'trsf_cls_cor',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: pageState === 'disposal' && !!arm ? true : false,
    cellClass: pageState === 'disposal' && !!arm ? 'editable-ag-grid-cell' : '',
  },
  {
    headerName: t('fields.standardQuantity'),
    field: 'trsf_qty_cor',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
  {
    headerName: t('fields.openingMass'),
    field: 'trsf_open_kg',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: pageState === 'disposal' && !!arm ? true : false,
    cellClass: pageState === 'disposal' && !!arm ? 'editable-ag-grid-cell' : '',
  },
  {
    headerName: t('fields.closingMass'),
    field: 'trsf_close_kg',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: pageState === 'disposal' && !!arm ? true : false,
    cellClass: pageState === 'disposal' && !!arm ? 'editable-ag-grid-cell' : '',
  },
  {
    headerName: t('fields.massQuantity'),
    field: 'trsf_load_kg',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
];

export default columns;
