const columns = (t) => [
  {
    headerName: t('fields.id'),
    field: 'pmv_number',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    // pinned: 'left',
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.sourceUnit'),
    field: 'pmv_srccode',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.destinationUnit'),
    field: 'pmv_dstcode',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.product'),
    field: 'pmv_prdctlnk',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.batch'),
    field: 'pmv_batchcode',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.state'),
    field: 'pmv_status_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.quantity'),
    field: 'pmv_moved_qty',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
  },
];

export default columns;
