#!/bin/sh

export HMI_ORIGIN_IP="10.1.10.66"
export HMI_ORIGIN_PORT=8000
export HMI_ORIGIN_PROTO="https"

export HMI_PROTO="https"
export HMI_PORT="8443"

export OMEGA_USER="messages"
export OMEGA_PWD="abcd1234"
export OMEGA_DBASE="OML5K"
export OMEGA_DBPORT="1521"

npm start
