#!/bin/sh

export MSGBROKER_ORIGIN_IP="10.1.10.66"
export MSGBROKER_ORIGIN_PORT=8000
export MSGBROKER_PROTO="https"

export OMEGA_USER="messages"
export OMEGA_PWD="abcd1234"
export OMEGA_DBASE="OML5K"
export OMEGA_DBPORT="1521"

npm start
