const columns = (t, values, form) => [
  {
    headerName: t('fields.status'),
    field: 'status',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    width: 90,
    cellRenderer: 'SwitchRender',
    // cellEditor: 'SwitchEditor',
    // cellEditorParams: {
    //   values: "hello",
    //   form: form,
    // },
  },
  {
    headerName: t('fields.templateName'),
    field: 'template_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
  },
  {
    headerName: t('fields.locale'),
    field: 'locale',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 90,
  },
  {
    headerName: t('fields.templateType'),
    field: 'template_type_desc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 110,
  },
  // {
  //   headerName: t('fields.templateIdentifier'),
  //   field: 'template_code',
  //   filter: 'FuzzyFilter',
  //   sortable: true,
  //   resizable: true,
  // },
  {
    headerName: t('fields.defaultTemplate'),
    field: 'default_flag',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'SwitchRender',
    width: 120,
  },
  {
    headerName: t('fields.numOfCopies'),
    field: 'copies',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 110,
  },
  {
    headerName: t('fields.footerText'),
    field: 'footers',
    filter: 'FuzzyFilter',
    cellEditor: 'FooterEditor',
    sortable: true,
    resizable: true,
    editable: true,
    cellEditorParams: {
      values: "hello",
      form: form,
    },
    width: 120,
  },
  {
    headerName: t('fields.email'),
    field: 'email',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: true,
  },
  {
    headerName: t('fields.print'),
    field: 'send_to_printer',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'SwitchRender',
    width: 80,
  },
  // {
  //   headerName: t('fields.tiggerPoint'),
  //   field: '',
  //   filter: 'FuzzyFilter',
  //   sortable: true,
  //   resizable: true,
  // },
];

export default columns;
