const columns = (t) => [
  {
    headerName: t('fields.status'),
    field: 'status',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    width: 90,
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.templateName'),
    field: 'template_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
  },
  {
    headerName: t('fields.locale'),
    field: 'locale',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 110,
  },
  {
    headerName: t('fields.templateType'),
    field: 'template_type',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 110,
  },
  // {
  //   headerName: t('fields.templateIdentifier'),
  //   field: 'template_code',
  //   filter: 'FuzzyFilter',
  //   sortable: true,
  //   resizable: true,
  // },
  {
    headerName: t('fields.defaultTemplate'),
    field: 'default_flag',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 150,
  },
  {
    headerName: t('fields.numOfCopies'),
    field: 'copies',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 110,
  },
  {
    headerName: t('fields.footerText'),
    field: 'footers',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: true,
  },
  {
    headerName: t('fields.email'),
    field: 'email',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: true,
  },
  // {
  //   headerName: t('fields.tiggerPoint'),
  //   field: '',
  //   filter: 'FuzzyFilter',
  //   sortable: true,
  //   resizable: true,
  // },
];

export default columns;
