<?php
function getBayviewServerConfiguration()
{
	// shellTGI
	$bayviewBayServers=array(
		'BAY01L'=>array(
			'bay_code'=>'BAY01L', 
			'cfg_file'=>'data_config4bay1L.json', 
			'server_url'=>'http://localhost:3001/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY01R'=>array(
			'bay_code'=>'BAY01R', 
			'cfg_file'=>'data_config4bay1R.json', 
			'server_url'=>'http://localhost:3011/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY02L'=>array(
			'bay_code'=>'BAY02L', 
			'cfg_file'=>'data_config4bay2L.json', 
			'server_url'=>'http://localhost:3002/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY02R'=>array(
			'bay_code'=>'BAY02R', 
			'cfg_file'=>'data_config4bay2R.json', 
			'server_url'=>'http://localhost:3012/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY005'=>array(
			'bay_code'=>'BAY005', 
			'cfg_file'=>'data_config4bay5.json', 
			'server_url'=>'http://localhost:3005/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		)
	);
	
	return $bayviewBayServers;
}
?>
