<?php
function getBayviewServerConfiguration()
{
	// shellPGI
	$bayviewBayServers=array(
		'BAY001'=>array(
			'bay_code'=>'BAY001', 
			'cfg_file'=>'data_config4bay1.json', 
			'server_url'=>'http://localhost:3001/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY002'=>array(
			'bay_code'=>'BAY002', 
			'cfg_file'=>'data_config4bay2.json', 
			'server_url'=>'http://localhost:3002/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY003'=>array(
			'bay_code'=>'BAY003', 
			'cfg_file'=>'data_config4bay3.json', 
			'server_url'=>'http://localhost:3003/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>false
		),
		'BAY004'=>array(
			'bay_code'=>'BAY004', 
			'cfg_file'=>'data_config4bay4.json', 
			'server_url'=>'http://localhost:3004/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>false
		),
		'BAY005'=>array(
			'bay_code'=>'BAY005', 
			'cfg_file'=>'data_config4bay5.json', 
			'server_url'=>'http://localhost:3005/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		)
	);
	
	return $bayviewBayServers;
}
?>
