/*
    Add the following new columns in table PRODUCTS for the feature of Cross Over Protection at a terminal:
    PROD_GUARDMASTER_CODE: A new field to allow entry of a 4 char PID product code for sending to RTC.
    PROD_GUARDMASTER_QUALITY: A new field against the drawer product, allowing the drawer product quality to be specified and sent to the RTC.
*/

alter table PRODUCTS add PROD_GUARDMASTER_CODE VARCHAR2(4);
alter table PRODUCTS add PROD_GUARDMASTER_QUALITY NUMBER(3);


-- create a new table to manage product quality records
CREATE TABLE PRODUCT_QUALITYS
(
    QUALITY_ID               NUMBER(3)   NOT NULL,
    QUALITY_CODE             VARCHAR2(8)   NOT NULL,
    QUALITY_NAME             VARCHAR2(100),
    QUALITY_DESC             VARCHAR2(200),
    QUALITY_ACTIVE           VARCHAR2(2),
    QUALITY_CREATED          DATE            DEFAULT SYSDATE NOT NULL,
    QUALITY_UPDATED          DATE            DEFAULT SYSDATE NOT NULL,
    QUALITY_USER             VARCHAR2(12),
    CONSTRAINT PK_PRODUCT_QUALITYS
    PRIMARY KEY(QUALITY_ID)
);

ALTER TABLE PRODUCT_QUALITYS
  ADD CONSTRAINT UK_PRODUCT_QUALITYS UNIQUE (QUALITY_CODE);

-- initialize the table with data
INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (0, '00000000', 'Not specified', 'Not specified, e.g. vapour or returns', 'N', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (91, '01011011', 'RON 91', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (92, '01011100', 'RON 92', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (93, '01011101', 'RON 93', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (94, '01011110', 'RON 94', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (95, '01011111', 'RON 95', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (96, '01100000', 'RON 96', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (97, '01100001', 'RON 97', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (98, '01100010', 'RON 98', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (99, '01100011', 'RON 99', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (100, '01100100', 'RON 100', '', 'Y', SYSDATE, SYSDATE, '9999');


INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (66, '01000010', 'Diesel (truck diesel)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (67, '01000011', 'Vegetable oil', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (68, '01000100', 'Diesel (standard)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (69, '01000101', 'Heating oil (standard)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (70, '01000110', 'Diesel (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (71, '01000111', 'Heating oil (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (72, '01001000', 'FAME', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (73, '01001001', 'Kerosine / heating', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (74, '01001010', 'Kerosine / jet', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (75, '01001011', 'Avgas', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (76, '01001100', 'Diesel (low sulphur)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (77, '01001101', 'Diesel (dyed blue)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (78, '01001110', 'Heating oil (low sulphur)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (79, '01001111', 'Not used', 'Not used', 'N', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (80, '01010000', 'Methyl alcohol (pure, for motors)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (81, '01010001', 'Ethyl alcohol (taxed)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (82, '01010010', 'Ethyl alcohol (exempt from tax)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (83, '01010011', 'Not used', 'Not used', 'N', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (84, '01010100', 'E50 (Petrol95 with an admixture of 21% to 74% ethyl alcohol)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (85, '01010101', 'E85 (Petrol95 with an admixture of 75% to 98% ethyl alcohol)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (86, '01010110', 'Others', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (219, '11011011', 'RON 91 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (220, '11011100', 'RON 92 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (221, '11011101', 'RON 93 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (222, '11011110', 'RON 94 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (223, '11011111', 'RON 95 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (224, '11100000', 'RON 96 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (225, '11100001', 'RON 97 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (226, '11100010', 'RON 98 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (227, '11100011', 'RON 99 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

INSERT INTO PRODUCT_QUALITYS (QUALITY_ID, QUALITY_CODE, QUALITY_NAME, QUALITY_DESC,  QUALITY_ACTIVE, QUALITY_CREATED, QUALITY_UPDATED, QUALITY_USER)
VALUES (228, '11100100', 'RON 100 (variant 2)', '', 'Y', SYSDATE, SYSDATE, '9999');

COMMIT;


-- update GUI_PRODUCTS to add new columns
CREATE OR REPLACE FORCE VIEW GUI_PRODUCTS AS
select
	prod.PROD_CODE					as PROD_CODE
	, prod.PROD_CMPY				as PROD_CMPYCODE
	, dcmp.CMPY_NAME				as PROD_CMPYNAME
	, prod.PROD_NAME				as PROD_NAME
	, prod.PROD_PROD_GROUP			as PROD_GROUP
	, pgrp.PGR_DESCRIPTION			as PROD_GROUPNAME
	, prod.PROD_PRICE				as PROD_PRICE
	, prod.PROD_PRICE_UNIT			as PROD_PRICEUNIT
	, prod.PROD_CLASS				as PROD_CLASS
	, gprd.GEN_PROD_DESC			as PROD_CLASSDESC
	, prod.PROD_TXT_COLOUR			as PROD_TEXTCOLOR
	, prod.PROD_BACK_COLOUR			as PROD_BACKCOLOR
	, prod.PROD_IMAGE				as PROD_IMAGE
	, prod.PROD_RPT_UNIT			as PROD_RPTUNIT
	, unit.DESCRIPTION				as PROD_RPTUNITNAME
	, prod.PROD_RPT_TEMP			as PROD_RPTTEMP
	, prod.PROD_NUMBER				as PROD_NUMBER
	, prod.PROD_IS_LOCKED			as PROD_IS_LOCKED
	, prod.PROD_IS_BLEND			as PROD_IS_BLEND
	, prod.PROD_LDTOL_FLAG			as PROD_LDTOL_FLAG
	, prod.PROD_LDTOL_PTOL			as PROD_LDTOL_PTOL
	, prod.PROD_LDTOL_NTOL			as PROD_LDTOL_NTOL
	, prod.PROD_IS_COMPLIANT 		as PROD_IS_COMPLIANT
	, pflg.PROD_CHECK_HOT_VOLUME	as PROD_CHECK_HOT_VOLUME
	, prod.PROD_15_DENSITY			as PROD_15_DENSITY
	, prod.PROD_HOT_TEMP			as PROD_HOT_TEMP
	, prod.PROD_CHECK_2ND_DRAWER	as PROD_CHECK_2ND_DRAWER
	, prod.PROD_2ND_DRAWER			as PROD_2ND_DRAWER
	, dcmp2.CMPY_NAME				as PROD_2ND_DRAWER_NAME
	, prod.PROD_2ND_PRODUCT			as PROD_2ND_PRODUCT
	, prod.PROD_DESC    			as PROD_DESC
	, prod2.PROD_NAME				as PROD_2ND_PRODUCT_NAME
    , prod.PROD_GUARDMASTER_CODE    as PROD_GUARDMASTER_CODE
    , prod.PROD_GUARDMASTER_QUALITY as PROD_GUARDMASTER_QUALITY
    , qlty.QUALITY_CODE             as PROD_GUARDMASTER_QLTYCODE
    , qlty.QUALITY_NAME             as PROD_GUARDMASTER_QLTYNAME
	, hzch.HZCF_ID					as PROD_HAZID
	, hzch.HZCF_NAME				as PROD_HAZNAME
	, hzch.HZCF_CLASS				as PROD_HAZCLASS
	, hzch.HZCF_HZ_CODE				as PROD_HAZCODE
	, hzch.HZCF_SUB_RISK			as PROD_HAZRISK
	, hzch.HZCF_EMRG				as PROD_HAZEMRG
	, hzch.HZCF_PACK_GROUP			as PROD_HAZPACKGRP
	, hzch.HZCF_PACK_METHOD			as PROD_HAZPACKMTHD
from
	PRODUCTS						prod
	, GUI_COMPANYS					dcmp
	, PRODUCT_GROUP					pgrp
	, UNIT_SCALE_VW					unit
	, HZ_LINK						hzlk
	, HAZCHEM						hzch
	, (
			select
				gp.GEN_PROD_CODE
				, decode( gu.PROD_COUNT, NULL, 0, gu.PROD_COUNT) 									as PROD_COUNT
				, gp.GEN_PROD_CODE||' ('||decode( gu.PROD_COUNT, NULL, 0, gu.PROD_COUNT)||') ' 		as GEN_PROD_DESC
			from
				GENERIC_PROD  gp
				, (
					select PROD_CLASS, count(PROD_CODE) as PROD_COUNT from PRODUCTS where 1=1 group by PROD_CLASS
				) gu
			where
				gp.GEN_PROD_CODE = gu.PROD_CLASS(+)
	) gprd
	, (
		select
			rt.RAT_PROD_PRODCMPY
			, rt.RAT_PROD_PRODCODE
			, max(NVL(bp.BASE_LIMIT_PRESET_HT,0)) as 				PROD_CHECK_HOT_VOLUME
		from
			RATIOS			rt
			, BASE_PRODS 	bp
		where rt.RATIO_BASE=bp.BASE_CODE
		group by rt.RAT_PROD_PRODCMPY, rt.RAT_PROD_PRODCODE
	) pflg
	, GUI_COMPANYS					dcmp2
	, PRODUCTS						prod2
    , PRODUCT_QUALITYS              qlty
where
	( ( (SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') = 'N') and (dcmp.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE')) )
	or ( SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE') IS NULL )
	or ( SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') = 'Y' )
	or ( SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') IS NULL) )
	and prod.PROD_CODE = pflg.RAT_PROD_PRODCODE(+)
	and prod.PROD_CMPY = pflg.RAT_PROD_PRODCMPY(+)
	and prod.PROD_CMPY = dcmp.CMPY_CODE
	and prod.PROD_PROD_GROUP = pgrp.PGR_CODE(+)
	and prod.PROD_RPT_UNIT = unit.UNIT_ID(+)
	and prod.PROD_CMPY = hzlk.HZLNK_SP_PRODCMPY(+)
	and prod.PROD_CODE = hzlk.HZLNK_SP_PRODCODE(+)
	and hzlk.HZ_LINK_ID = hzch.HZCF_ID(+)
	and prod.PROD_CLASS = gprd.GEN_PROD_CODE(+)
	and prod.PROD_2ND_DRAWER = dcmp2.CMPY_CODE(+)
	and prod.PROD_2ND_DRAWER = prod2.PROD_CMPY(+)
	and prod.PROD_2ND_PRODUCT = prod2.PROD_CODE(+)
    and prod.PROD_GUARDMASTER_QUALITY = qlty.QUALITY_ID(+)
/
