ALTER TABLE SPECVARS MODIFY SCHVSPID_SHLSTRIP NUMBER(15);


ALTER TABLE COMPANYS MODIFY CMPY_TRIP_STRT NUMBER(15);
ALTER TABLE COMPANYS MODIFY CMPY_TRIP_END NUMBER(15);
ALTER TABLE COMPANYS MODIFY CMPY_TRIP_LAST NUMBER(15);
ALTER TABLE COMPANYS MODIFY CMPY_ORD_STRT NUMBER(15);
ALTER TABLE COMPANYS MODIFY CMPY_ORD_END NUMBER(15);
ALTER TABLE COMPANYS MODIFY CMPY_ORD_LAST NUMBER(15);

