
/*
  drop an extra primary key FOLIO_INDEX in table CLOSEOUT_TANK to handle sub folios when base product is changed in tank during the parent folio
*/
ALTER TABLE CLOSEOUT_TANK
DROP CONSTRAINT CLOSEOUT_TANK_PK;
-- DROP INDEX CLOSEOUT_TANK_PK;

ALTER TABLE CLOSEOUT_TANK DROP COLUMN FOLIO_INDEX;
ALTER TABLE CLOSEOUT_TANK DROP COLUMN OPEN_FOLIO_TIME;
ALTER TABLE CLOSEOUT_TANK DROP COLUMN CLOSE_FOLIO_TIME;

ALTER TABLE CLOSEOUT_TANK
-- ADD CONSTRAINT CLOSEOUT_TANK_PK PRIMARY KEY (CLOSEOUT_NR, TANK_TERMINAL, TANK_CODE, FOLIO_INDEX);
ADD CONSTRAINT CLOSEOUT_TANK_PK PRIMARY KEY (CLOSEOUT_NR, TANK_TERMINAL, TANK_CODE);



/*
  drop an extra primary key FOLIO_INDEX in table CLOSEOUT_TK_OWNER to handle sub folios when base product is changed in tank during the parent folio
*/
ALTER TABLE CLOSEOUT_TK_OWNER
DROP CONSTRAINT PK_CLOSEOUT_TK_OWNER;
-- DROP INDEX PK_CLOSEOUT_TK_OWNER;

ALTER TABLE CLOSEOUT_TK_OWNER DROP COLUMN FOLIO_INDEX;

ALTER TABLE CLOSEOUT_TK_OWNER
-- ADD CONSTRAINT PK_CLOSEOUT_TK_OWNER PRIMARY KEY (CLOSEOUT_NR, TKCMPY_LINK, TKLINK_TANKCODE, TKLINK_TANKDEPO, FOLIO_INDEX);
ADD CONSTRAINT PK_CLOSEOUT_TK_OWNER PRIMARY KEY (CLOSEOUT_NR, TKCMPY_LINK, TKLINK_TANKCODE, TKLINK_TANKDEPO);



/*
  drop an extra primary key FOLIO_INDEX in table CLOSEOUT_PRODOWNSHIP to handle sub folios when base product is changed in tank during the parent folio
*/
ALTER TABLE CLOSEOUT_PRODOWNSHIP
DROP CONSTRAINT CLOSEOUT_PRODOWNSHIP_PK;
-- DROP INDEX CLOSEOUT_PRODOWNSHIP_PK;

ALTER TABLE CLOSEOUT_PRODOWNSHIP DROP COLUMN FOLIO_INDEX;

ALTER TABLE CLOSEOUT_PRODOWNSHIP
-- ADD CONSTRAINT CLOSEOUT_PRODOWNSHIP_PK PRIMARY KEY (CLOSEOUT_NR, CMPY_CODE, BASE_CODE, FOLIO_INDEX);
ADD CONSTRAINT CLOSEOUT_PRODOWNSHIP_PK PRIMARY KEY (CLOSEOUT_NR, CMPY_CODE, BASE_CODE);



/*
  drop an extra primary key FOLIO_INDEX in table CLOSEOUT_METER to handle sub folios when base product is changed in tank during the parent folio
*/
ALTER TABLE CLOSEOUT_METER
DROP CONSTRAINT CLOSEOUT_METER_PK;
-- DROP INDEX CLOSEOUT_METER_PK;

ALTER TABLE CLOSEOUT_METER DROP COLUMN FOLIO_INDEX;

ALTER TABLE CLOSEOUT_METER
-- ADD CONSTRAINT CLOSEOUT_METER_PK PRIMARY KEY (CLOSEOUT_NR, METER_CODE, FOLIO_INDEX);
ADD CONSTRAINT CLOSEOUT_METER_PK PRIMARY KEY (CLOSEOUT_NR, METER_CODE);
