/*
ALLOC_INDEX      NOT NULL NUMBER(4)      
ALLOC_TYPE       NOT NULL NUMBER(2)      
ALLOC_TYPENAME            VARCHAR2(255)  
ALLOC_CMPYCODE   NOT NULL VARCHAR2(16)   
ALLOC_CMPYNAME            VARCHAR2(300)  
ALLOC_SUPPCODE   NOT NULL VARCHAR2(16)   
ALLOC_SUPPNAME            VARCHAR2(300)  
ALLOC_OWNERCODE           VARCHAR2(16)   
ALLOC_OWNERNAME           VARCHAR2(300)  
ALLOC_LOCK                NUMBER(2)      
ALLOC_LOCKNAME            VARCHAR2(255)  
ALLOC_PERIOD              NUMBER(2)      
ALLOC_PERIODNAME          VARCHAR2(255)  
ALLOC_DATETIME            DATE           
ALLOC_START_DATE          DATE           
ALLOC_END_DATE            DATE           
ALLOC_NEXT_DATE           DATE           
ALLOC_COMMENTS            VARCHAR2(1000) 
ALLOC_TYPEDESC            VARCHAR2(298)  
ALLOC_CMPYDESC            VARCHAR2(319)  
ALLOC_SUPPDESC            VARCHAR2(319)  
ALLOC_OWNERDESC           VARCHAR2(319)  
ALLOC_LOCKDESC            VARCHAR2(298)  
ALLOC_PERIODDESC          VARCHAR2(298)  
ALLOC_BASEFLAG            VARCHAR2(1)    

AITEM_INDEX    NOT NULL NUMBER(4)     
AITEM_TYPE     NOT NULL NUMBER(2)     
AITEM_TYPENAME          VARCHAR2(255) 
AITEM_CMPYCODE NOT NULL VARCHAR2(16)  
AITEM_CMPYNAME          VARCHAR2(300) 
AITEM_PRODCODE NOT NULL VARCHAR2(36)  
AITEM_PRODNAME          VARCHAR2(40)  
AITEM_SUPPCODE NOT NULL VARCHAR2(16)  
AITEM_SUPPNAME          VARCHAR2(300) 
AITEM_QTYLIMIT          FLOAT(126)    
AITEM_QTYUSED           NUMBER        
AITEM_QTYLEFT           FLOAT(126)    
AITEM_PRODUNIT          NUMBER(2)     
AITEM_UNITNAME          VARCHAR2(255) 
AITEM_PERCHILD          NUMBER(4)     
*/

/*
    create a view to link the allocations, allocaiton products, and customer accounts
*/

CREATE OR REPLACE VIEW GUI_ALLOCATION_PRODUCTS
AS
SELECT 
    DECODE(TO_CHAR(ALLOC.ALLOC_TYPE), '3', cust.CUST_ACCT, NULL) as ALLOC_CUSTACCT,
    alloc.*, 
    aprod.*
FROM 
    GUI_ALLOCATIONS alloc, 
    GUI_ALLOCATION_ITEMS aprod,
    CUSTOMER cust
WHERE 
    alloc.ALLOC_INDEX = aprod.AITEM_INDEX
    AND alloc.ALLOC_TYPE = aprod.AITEM_TYPE
    AND alloc.ALLOC_CMPYCODE = aprod.AITEM_CMPYCODE
    AND alloc.ALLOC_SUPPCODE = aprod.AITEM_SUPPCODE
    AND DECODE(alloc.ALLOC_SUPPCODE, 'BaSePrOd', alloc.ALLOC_OWNERCODE, alloc.ALLOC_SUPPCODE) = cust.CUST_SUPP(+)
    AND alloc.ALLOC_CMPYCODE = cust.CUST_CODE(+)
/

