/*
    create a view to link the BaSePrOd products and the customers based on the data in table CUSTOMER_PRODUCT and RATIOS.
    CUSTOMER_PRODUCT:
    CUST_ACCT	VARCHAR2(40 BYTE)
    PROD_CODE	VARCHAR2(36 BYTE)
    PROD_CMPY	VARCHAR2(16 BYTE)
    COMMENT	    VARCHAR2(40 BYTE)

    RATIOS:
    RATIO_BASE	VARCHAR2(20 BYTE)
    RAT_PROD_PRODCODE	VARCHAR2(36 BYTE)
    RAT_PROD_PRODCMPY	VARCHAR2(16 BYTE)
    RATIO_VALUE	NUMBER(9,0)
    RAT_BLTOL_FLAG	NUMBER(2,0)
    RAT_BLTOL_PTOL	FLOAT
    RAT_BLTOL_NTOL	FLOAT
    RAT_HOT_MAIN	VARCHAR2(1 BYTE)
    RATIO_PERCENT_PPM	NUMBER(13,4)    
*/

CREATE OR REPLACE VIEW CUSTOMER_PRODUCTS_VW
AS
SELECT
    CA.CUST_SUPP
    , CA.CUST_CODE
    , CP.CUST_ACCT
    , CP.PROD_CODE
    , CP.PROD_CMPY
    , CP."COMMENT"
FROM
    CUSTOMER_PRODUCT  CP
    , CUSTOMER        CA
WHERE
    CP.CUST_ACCT = CA.CUST_ACCT
UNION
SELECT distinct
    CUST.CUST_SUPP
    , CUST.CUST_CODE
    , CPRD.CUST_ACCT
    , BRAT.RAT_PROD_PRODCODE  AS PROD_CODE
    , BRAT.RAT_PROD_PRODCMPY  AS PROD_CMPY
    , 'Base Product'          AS "COMMENT"
FROM
    CUSTOMER_PRODUCT  CPRD
    , CUSTOMER        CUST
    , RATIOS          PRAT
    , RATIOS          BRAT
WHERE
    CPRD.CUST_ACCT = CUST.CUST_ACCT
    AND CPRD.PROD_CODE = PRAT.RAT_PROD_PRODCODE
    AND CPRD.PROD_CMPY = PRAT.RAT_PROD_PRODCMPY
    AND PRAT.RATIO_BASE = BRAT.RATIO_BASE
    AND BRAT.RAT_PROD_PRODCMPY = 'BaSePrOd'
/



/*
SELECT distinct
    CPRD.CUST_ACCT
    , BRAT.RATIO_BASE  AS PROD_CODE
    , 'BaSePrOd'       AS PROD_CMPY
    , 'Base Product'   AS "COMMENT"
FROM
    CUSTOMER_PRODUCT  CPRD
    , RATIOS          BRAT
WHERE
    CPRD.PROD_CODE = BRAT.RAT_PROD_PRODCODE
    AND CPRD.PROD_CMPY = BRAT.RAT_PROD_PRODCMPY
*/