
drop table URBAC_USER_COLUMNS;


create table URBAC_USER_COLUMNS
(
    COLUMN_USER              VARCHAR2(12)    NOT NULL,
    COLUMN_SITE              VARCHAR2(16)    NOT NULL,
    COLUMN_PAGE              VARCHAR2(100)   NOT NULL,
    COLUMN_CODE              VARCHAR2(100)   NOT NULL,
    COLUMN_TITLE             VARCHAR2(200)   NOT NULL,
    COLUMN_VISIBLE           NUMBER(1)       DEFAULT 1,
    COLUMN_ORDER             NUMBER(9),
    COLUMN_PINNED            VARCHAR2(100),
    COLUMN_TYPE              VARCHAR2(100),
    COLUMN_FILTER            VARCHAR2(100),
    COLUMN_EDITOR            VARCHAR2(1000),
    COLUMN_RENDER            VARCHAR2(1000),
    COLUMN_STYLE             VARCHAR2(100),
    COLUMN_EDITABLE          NUMBER(1)       DEFAULT 0,
    COLUMN_SORTABLE          NUMBER(1)       DEFAULT 1,
    COLUMN_RESIZABLE         NUMBER(1)       DEFAULT 1,
    COLUMN_WIDTH             NUMBER(9)       DEFAULT 100,
    CONSTRAINT PK_URBAC_USER_COLUMNS PRIMARY KEY(COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE)
);


insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_terminal', 'fields.terminal', 1, 1, 'left', 'STRING', 'MultiFilter', '', '', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_trip_no', 'fields.tripNumber', 1, 2, 'left', 'INTEGER', 'FuzzyFilter', '', '', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_trip_no_org', 'fields.origin', 1, 3, '', 'INTEGER', 'FuzzyFilter', '', '', '', 0, 1, 1, 140);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_srctype_desc', 'fields.sourceTrip', 1, 4, '', 'STRING', 'MultiFilter', '', 'SourceRender', '', 0, 1, 1, 130);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_cnvrt_trace', 'fields.schdConvertTrace', 1, 5, '', 'STRING', 'MultiFilter', '', 'ConvertTraceRender, {t:t,}', '', 0, 1, 1, 130);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_caldate', 'fields.schedDate', 1, 6, '', 'DATETIME', '', '', 'DateRenderer', '', 0, 1, 1, 150);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_status', 'fields.tripStatus', 1, 7, '', 'STRING', 'MultiFilter', '', '', '', 0, 1, 1, 140);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'carrier_code', 'fields.carrierCode', 1, 8, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 140);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'carrier', 'fields.carrierName', 1, 9, '', 'STRING', 'MultiFilter', '', '', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'tnkr_code', 'fields.tankerCode', 1, 10, '', 'STRING', 'FuzzyFilter', '', 'LinkRenderer, {endpoint: TANKER_LIST, field: "tanker", index: "tnkr_code",}', '', 0, 1, 1, 130);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'tnkr_name', 'fields.tankerName', 1, 11, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 130);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'supplier_code', 'fields.supplierCode', 1, 12, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'supplier', 'fields.supplier', 1, 13, '', 'STRING', 'MultiFilter', '', '', '', 0, 1, 1, 140);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_priority', 'fields.priority', 1, 14, '', 'INTEGER', '', '', '', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shl_fleet_data', 'fields.hostData', 1, 15, '', 'STRING', '', '', '', '', 0, 1, 1, 130);


insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'order_cust_ordno', 'fields.orderNumber', 1, 16, '', 'INTEGER', 'FuzzyFilter', '', '', '', 0, 1, 1, 150);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'order_cust', 'fields.customerAcctOfOrder', 1, 17, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 220);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'order_cust_cmpy_code', 'fields.customerCodeOfOrder', 1, 18, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 200);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'order_cust_cmpy_name', 'fields.customerNameOfOrder', 1, 19, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 210);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_cust', 'fields.customerAcctOfTrip', 1, 20, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 210);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_cust_cmpycode', 'fields.customerCodeOfTrip', 1, 21, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 200);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_cust_cmpyname', 'fields.customerNameOfTrip', 1, 22, '', 'STRING', 'FuzzyFilter', '', '', '', 0, 1, 1, 200);


insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_ld_start', 'fields.loadStart', 1, 23, '', 'DATETIME', '', '', 'DateRenderer', '', 0, 1, 1, 150);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_ld_end', 'fields.loadEnd', 1, 24, '', 'DATETIME', '', '', 'DateRenderer', '', 0, 1, 1, 150);


insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'unload', 'fields.unload', 1, 25, '', 'BOOLEAN', '', '', 'BooleanRenderer', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_exp2', 'fields.loadExpiry', 1, 26, '', 'DATETIME', '', '', 'DateRenderer', '', 0, 1, 1, 150);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'reversed', 'fields.reversed', 1, 27, '', 'BOOLEAN', '', '', 'BooleanRenderer', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'archived', 'fields.archived', 1, 28, '', 'BOOLEAN', '', '', 'BooleanRenderer', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_supp_org', 'fields.supplierOrigin', 1, 29, '', 'STRING', '', '', '', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shlsload_load_id', 'fields.loadId', 1, 30, '', 'INTEGER', '', '', '', '', 0, 1, 1, 90);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'operator', 'fields.lastModifiedBy', 1, 31, '', 'STRING', '', '', '', '', 0, 1, 1, 140);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'last_chg_time', 'fields.lastModified', 1, 32, '', 'DATETIME', '', '', 'DateRenderer', '', 0, 1, 1, 150);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_sold_to_num', 'fields.soldTo', 1, 33, '', 'STRING', '', '', '', '', 0, 1, 1, 120);

insert into URBAC_USER_COLUMNS (COLUMN_USER, COLUMN_SITE, COLUMN_PAGE, COLUMN_CODE, COLUMN_TITLE, COLUMN_VISIBLE, COLUMN_ORDER, COLUMN_PINNED, COLUMN_TYPE, COLUMN_FILTER, COLUMN_EDITOR, COLUMN_RENDER, COLUMN_STYLE, COLUMN_EDITABLE, COLUMN_SORTABLE, COLUMN_RESIZABLE, COLUMN_WIDTH) 
values ('ANY_USER', 'ANY_SITE', 'M_LOADSCHEDULES', 'shls_ship_to_num', 'fields.shipTo', 1, 34, '', 'STRING', '', '', '', '', 0, 1, 1, 120);

COMMIT;
