/*
	add contents for Folio Status Types
*/

delete from MSG_LOOKUP where MSG_ID in (3080,3081,3082);

commit;

insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3080, 'ENG', 'Open');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3081, 'ENG', 'Frozen');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3082, 'ENG', 'Closed');

insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3080, 'CHN', '开放');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3081, 'CHN', '已冻结');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3082, 'CHN', '已终止');

commit;

delete from ENUMITEM where ENUMTYPENAME='FOLIO_STATUS_TYPE';

insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('FOLIO_STATUS_TYPE', 0, 'O', 3080);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('FOLIO_STATUS_TYPE', 1, 'F', 3081);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('FOLIO_STATUS_TYPE', 2, 'C', 3082);

commit;


-- Add VIEW for Folio Status Types

CREATE OR REPLACE VIEW FOLIO_STATUS_TYPES
(FOLIO_STATUS_ID, FOLIO_STATUS_CODE, FOLIO_STATUS_NAME)
AS 
SELECT 
	ENUMITEM.ENUM_NO FOLIO_STATUS_ID
	, ENUMITEM.ENUM_CODE FOLIO_STATUS_CODE
	, MSG_GLBL.MESSAGE FOLIO_STATUS_NAME
FROM ENUMITEM,MSG_GLBL
WHERE ENUMITEM.ENUM_TMM=MSG_GLBL.MSG_ID
AND ENUMTYPENAME='FOLIO_STATUS_TYPE';

/

commit;
