/*
	add contents for Schedule Source Types
*/

delete from MSG_LOOKUP where MSG_ID in (3070,3071,3072,3073,3074,3075);

commit;

insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3070, 'ENG', 'Unknown source');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3071, 'ENG', 'Created manually');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3072, 'ENG', 'Received from host');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3073, 'ENG', 'Generated by open order');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3074, 'ENG', 'Generated by system');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3075, 'ENG', 'Standalone or Special');

insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3070, 'CHN', '未知来源');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3071, 'CHN', '本地手工生成');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3072, 'CHN', '远程系统生成');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3073, 'CHN', '来自开放订单');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3074, 'CHN', '本地系统生成');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3075, 'CHN', '独立发油或特殊货单');

commit;

delete from ENUMITEM where ENUMTYPENAME='SHL_SOURCE_TYPE';

insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 0, 'U', 3070);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 1, 'M', 3071);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 2, 'H', 3072);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 3, 'O', 3073);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 4, 'S', 3074);

commit;


-- Add VIEW for Schedule Source Types

CREATE OR REPLACE VIEW SHL_SOURCE_TYPES
(SOURCE_TYPE_ID, SOURCE_TYPE_CODE, SOURCE_TYPE_NAME)
AS 
SELECT 
	ENUMITEM.ENUM_NO SOURCE_TYPE_ID
	, ENUMITEM.ENUM_CODE SOURCE_TYPE_CODE
	, MSG_GLBL.MESSAGE SOURCE_TYPE_NAME
FROM ENUMITEM,MSG_GLBL
WHERE ENUMITEM.ENUM_TMM=MSG_GLBL.MSG_ID
AND ENUMTYPENAME='SHL_SOURCE_TYPE';

/

commit;
