/*
    define the number of digits after decimal point for various variables having the NUMBER type
    API:            2
    TEMPERATURE:    2
    DENSITY:        3
    LEVEL:          0
    VOLUME:         0
    MASS:           0
    ADDITIVE:       3
    SG:             6
*/
delete from SITE_CONFIG where CONFIG_KEY='SITE_DEFAULT_PRECISION_API';
delete from SITE_CONFIG where CONFIG_KEY='SITE_DEFAULT_PRECISION_TEMPERATURE';
delete from SITE_CONFIG where CONFIG_KEY='SITE_DEFAULT_PRECISION_DENSITY';
delete from SITE_CONFIG where CONFIG_KEY='SITE_DEFAULT_PRECISION_LEVEL';
delete from SITE_CONFIG where CONFIG_KEY='SITE_DEFAULT_PRECISION_VOLUME';
delete from SITE_CONFIG where CONFIG_KEY='SITE_DEFAULT_PRECISION_MASS';
delete from SITE_CONFIG where CONFIG_KEY='SITE_DEFAULT_PRECISION_ADDITIVE';
delete from SITE_CONFIG where CONFIG_KEY='SITE_DEFAULT_PRECISION_SG';

commit;

insert into SITE_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_COMMENT, CONFIG_REQUIRED_BY_GUI) 
values ('SITE_DEFAULT_PRECISION_API', 2, 'API Precision', NULL );
insert into SITE_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_COMMENT, CONFIG_REQUIRED_BY_GUI) 
values ('SITE_DEFAULT_PRECISION_TEMPERATURE', 2, 'Temperature Precision', NULL );
insert into SITE_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_COMMENT, CONFIG_REQUIRED_BY_GUI) 
values ('SITE_DEFAULT_PRECISION_DENSITY', 3, 'Density Precision', NULL );
insert into SITE_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_COMMENT, CONFIG_REQUIRED_BY_GUI) 
values ('SITE_DEFAULT_PRECISION_LEVEL', 0, 'Level Precision', NULL );
insert into SITE_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_COMMENT, CONFIG_REQUIRED_BY_GUI) 
values ('SITE_DEFAULT_PRECISION_VOLUME', 0, 'Volume Quantity Precision', NULL );
insert into SITE_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_COMMENT, CONFIG_REQUIRED_BY_GUI) 
values ('SITE_DEFAULT_PRECISION_MASS', 0, 'Mass Quantity Precision', NULL );
insert into SITE_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_COMMENT, CONFIG_REQUIRED_BY_GUI) 
values ('SITE_DEFAULT_PRECISION_ADDITIVE', 3, 'Additive Precision', NULL );
insert into SITE_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_COMMENT, CONFIG_REQUIRED_BY_GUI) 
values ('SITE_DEFAULT_PRECISION_SG', 6, 'SG Precision', NULL );

commit;
