

/*
	add contents for ENUM STAGING_LOAD_MODE
*/

delete from MSG_LOOKUP where MSG_ID in (3354, 3355, 3356);

commit;

insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3354, 'ENG', 'Load Schedule');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3355, 'ENG', 'Pickup Schedule');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3356, 'ENG', 'Staged Schedule');

insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3354, 'CHN', '普通提单');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3355, 'CHN', '组合提单');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3356, 'CHN', '被组合提单');

commit;

delete from ENUMITEM where ENUMTYPENAME='STAGING_LOAD_MODE';

insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('STAGING_LOAD_MODE', 0, 'NL', 3354);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('STAGING_LOAD_MODE', 1, 'PL', 3355);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('STAGING_LOAD_MODE', 2, 'SL', 3356);

commit;


-- Add VIEW for Load Options in staging bay

CREATE OR REPLACE VIEW STAGING_LOAD_MODES
(STAGING_LOAD_MODE_ID, STAGING_LOAD_MODE_CODE, STAGING_LOAD_MODE_NAME)
AS 
SELECT 
	ENUMITEM.ENUM_NO STAGING_LOAD_MODE_ID
	, ENUMITEM.ENUM_CODE STAGING_LOAD_MODE_CODE
	, MSG_GLBL.MESSAGE STAGING_LOAD_MODE_NAME
FROM ENUMITEM,MSG_GLBL
WHERE ENUMITEM.ENUM_TMM=MSG_GLBL.MSG_ID
AND ENUMTYPENAME='STAGING_LOAD_MODE';

/

commit;




/*
	add contents for ENUM STAGING_LOAD_OPTION
*/

delete from MSG_LOOKUP where MSG_ID in (3350, 3351, 3352, 3353);

commit;

insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3350, 'ENG', 'No Check');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3351, 'ENG', 'Load Schedules only');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3352, 'ENG', 'Pickup Schedules only');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3353, 'ENG', 'Both Load and Pickup Schedules');

insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3350, 'CHN', '不用检查');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3351, 'CHN', '只允许普通提单');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3352, 'CHN', '只允许组合提单');
insert into MSG_LOOKUP (MSG_ID, LANG_ID, MESSAGE) values (3353, 'CHN', '允许普通提单与组合提单');

commit;

delete from ENUMITEM where ENUMTYPENAME='STAGING_LOAD_OPTION';

insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('STAGING_LOAD_OPTION', 0, 'NC', 3350);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('STAGING_LOAD_OPTION', 1, 'NL', 3351);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('STAGING_LOAD_OPTION', 2, 'PL', 3352);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('STAGING_LOAD_OPTION', 3, 'NP', 3353);

commit;


-- Add VIEW for Load Options in staging bay

CREATE OR REPLACE VIEW STAGING_LOAD_OPTIONS
(STAGING_LOAD_OPTION_ID, STAGING_LOAD_OPTION_CODE, STAGING_LOAD_OPTION_NAME)
AS 
SELECT 
	ENUMITEM.ENUM_NO STAGING_LOAD_OPTION_ID
	, ENUMITEM.ENUM_CODE STAGING_LOAD_OPTION_CODE
	, MSG_GLBL.MESSAGE STAGING_LOAD_OPTION_NAME
FROM ENUMITEM,MSG_GLBL
WHERE ENUMITEM.ENUM_TMM=MSG_GLBL.MSG_ID
AND ENUMTYPENAME='STAGING_LOAD_OPTION';

/

commit;

