
-- mockup pickup schedule
-- we have created 3 schedule: 834 and 835 are pre-schedule, 836 are pre-order

-- mockup SCHEDULE for 9998 - Pickup Schedule Company
Insert into SCHEDULE (SHL_TANKER,SHLS_TRIP_NO,SHLS_SUPP,SHLS_CALDATE,SHLS_SHIFT,SHLS_PROFILE,SHLS_REAL_PRF,SHL_MAVIS_TYPE,SHLS_DRAWER,SHL_SENT_TO_HOST,SHL_COMMS_LOCK,SHLS_PRIORITY,SHL_PRIME_MOVER,SHL_PRELOADER,SHL_RET_REP,SHL_DEL_REP,SHL_VAR_REP,SHL_OLD_REP,SHLS_AUTO_SCHED,RTN_STAT,SHL_CMPLT_MTHD,SHL_DURATN_MIN,SHLS_NTH_IN_SHIF,SHLS_ORIG_TKR,SHLS_DRIVER,SHLS_TERMINAL,SHLS_LD_TYPE,SHLS_AUTO_CODE,SHL_PASSED_ON,SHL_FLEET_DATA,SHL_DEBRIEFED,SHL_RET_LOC,SHL_IPM,SHLS_REF_NO,SHL_SENT_RSS,SHL_NOT_SENT_LOG,SHL_RSS_DEL,SHL_RSS_INFDEL,SHL_TRAILER1,SHL_TRAILER2,SHL_APPROVED,SHLS_APPR_TRM,SHL_IS_DRUMFILL,SHLSLOAD_LD_TRM,SHLSLOAD_LOAD_ID,SHLS_TRIP_NO_2,SHLS_SEAL_NO,OPERATOR,STATS,NR_LOADING_TRSA,LD_START,LD_END,SHLS_EXP,SHLS_CLASS,SHLS_IOTYPE,SHLS_IDOC_NUM,SHLS_SOLD_TO_NUM,SHLS_SHIP_TO_NUM,SHLS_3RD_ORDER,LAST_CHG_TIME,SHLS_TRIP_NO_ORG,SHLS_SUPP_ORG,SHLS_ISOTAINER_NUM,SHLS_SRCTYPE,SPEC_INSTRUCTIONS,SHLS_LOAD_SECURITY_INFO,SHLS_CUST,SHLS_CNVRT_TRACE,SHLS_CNVRT_TIME,SHL_HOST_REF_NO,SHL_PIDX_AUTH_NO,SHLS_PICKUP_MODE) 
values ('ZPKUP999',900001,'9998',SYSDATE,null,0,null,null,'1',null,null,null,43449135,null,null,null,null,null,'Y',0,0,0,0,'ZPKUP999',null,'11',2,0,'N',null,'N','11',null,'101010',null,null,null,null,null,null,null,'11','N','11',null,900001,null,'9999',null,null,null,null,SYSDATE+2,0,0,null,null,null,null,to_timestamp('18/MAY/23 04:07:18.000000000 PM','DD/MON/RR HH12:MI:SSXFF AM'),null,null,null,1,null,null,'104',null,null,null,null,1);


-- mockup SPECDETS for 9998 - Pickup Schedule Company

Insert into SPECDETS (SCHD_PMV_NUM,SCHDSPEC_SHLSTRIP,SCHDSPEC_SHLSSUPP,SCHD_COMP_ID,SCHDPROD_PRODCODE,SCHDPROD_PRODCMPY,SCHD_UNITS,SCHD_SPECQTY,SCHD_PRLDQTY,SCHD_ORDER,SCHD_SEAL_NUMBER,SCHD_TRAILER,SCHD_TRAILERCOMP,SCHD_FILLED,SCHD_TRSA_ID,SCHD_N_DRUMS,SCHD_DRUM_SZ,SCHD_DENSITY,SCHD_DELIVERED,SCHD_RPT_TEMP,SCHD_RPT_CFACTOR,SCHD_RPT_T_UNIT,SCHD_C_OF_E,SCHD_MASS_FRCTN,SCHD_HOST_DATA,ARMCODE,SCHD_TC_TODO,SCHD_PUB_TEMP,SCHD_PUB_VCF,SCHD_PUB_DENS,SCHD_PRESETQTY,SCHD_DELIV_NUM,SCHD_SOLD_TO_NUM,SCHD_SHIP_TO_NUM,SCHD_ISOTAINER_NUM,SCHD_VISCOSITY,SCHD_MASS_ORG_SCHD,SCHD_MASS_ORG_PRELOAD,FASTTRACK_CALL_TIME,FASTTRACK_START_TIME,FASTTRACK_END_TIME,FASTTRACK_BAY) 
values (null,900001,'9998',1,'141','1',5,10000,0,null,null,43449135,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null,null,null,null);
Insert into SPECDETS (SCHD_PMV_NUM,SCHDSPEC_SHLSTRIP,SCHDSPEC_SHLSSUPP,SCHD_COMP_ID,SCHDPROD_PRODCODE,SCHDPROD_PRODCMPY,SCHD_UNITS,SCHD_SPECQTY,SCHD_PRLDQTY,SCHD_ORDER,SCHD_SEAL_NUMBER,SCHD_TRAILER,SCHD_TRAILERCOMP,SCHD_FILLED,SCHD_TRSA_ID,SCHD_N_DRUMS,SCHD_DRUM_SZ,SCHD_DENSITY,SCHD_DELIVERED,SCHD_RPT_TEMP,SCHD_RPT_CFACTOR,SCHD_RPT_T_UNIT,SCHD_C_OF_E,SCHD_MASS_FRCTN,SCHD_HOST_DATA,ARMCODE,SCHD_TC_TODO,SCHD_PUB_TEMP,SCHD_PUB_VCF,SCHD_PUB_DENS,SCHD_PRESETQTY,SCHD_DELIV_NUM,SCHD_SOLD_TO_NUM,SCHD_SHIP_TO_NUM,SCHD_ISOTAINER_NUM,SCHD_VISCOSITY,SCHD_MASS_ORG_SCHD,SCHD_MASS_ORG_PRELOAD,FASTTRACK_CALL_TIME,FASTTRACK_START_TIME,FASTTRACK_END_TIME,FASTTRACK_BAY) 
values (null,900001,'9998',2,'141','1',5,10000,0,null,null,43449135,2,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null,null,null,null);
Insert into SPECDETS (SCHD_PMV_NUM,SCHDSPEC_SHLSTRIP,SCHDSPEC_SHLSSUPP,SCHD_COMP_ID,SCHDPROD_PRODCODE,SCHDPROD_PRODCMPY,SCHD_UNITS,SCHD_SPECQTY,SCHD_PRLDQTY,SCHD_ORDER,SCHD_SEAL_NUMBER,SCHD_TRAILER,SCHD_TRAILERCOMP,SCHD_FILLED,SCHD_TRSA_ID,SCHD_N_DRUMS,SCHD_DRUM_SZ,SCHD_DENSITY,SCHD_DELIVERED,SCHD_RPT_TEMP,SCHD_RPT_CFACTOR,SCHD_RPT_T_UNIT,SCHD_C_OF_E,SCHD_MASS_FRCTN,SCHD_HOST_DATA,ARMCODE,SCHD_TC_TODO,SCHD_PUB_TEMP,SCHD_PUB_VCF,SCHD_PUB_DENS,SCHD_PRESETQTY,SCHD_DELIV_NUM,SCHD_SOLD_TO_NUM,SCHD_SHIP_TO_NUM,SCHD_ISOTAINER_NUM,SCHD_VISCOSITY,SCHD_MASS_ORG_SCHD,SCHD_MASS_ORG_PRELOAD,FASTTRACK_CALL_TIME,FASTTRACK_START_TIME,FASTTRACK_END_TIME,FASTTRACK_BAY) 
values (null,900001,'9998',3,'141','1',5,10000,0,null,null,43449135,3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null,null,null,null);
Insert into SPECDETS (SCHD_PMV_NUM,SCHDSPEC_SHLSTRIP,SCHDSPEC_SHLSSUPP,SCHD_COMP_ID,SCHDPROD_PRODCODE,SCHDPROD_PRODCMPY,SCHD_UNITS,SCHD_SPECQTY,SCHD_PRLDQTY,SCHD_ORDER,SCHD_SEAL_NUMBER,SCHD_TRAILER,SCHD_TRAILERCOMP,SCHD_FILLED,SCHD_TRSA_ID,SCHD_N_DRUMS,SCHD_DRUM_SZ,SCHD_DENSITY,SCHD_DELIVERED,SCHD_RPT_TEMP,SCHD_RPT_CFACTOR,SCHD_RPT_T_UNIT,SCHD_C_OF_E,SCHD_MASS_FRCTN,SCHD_HOST_DATA,ARMCODE,SCHD_TC_TODO,SCHD_PUB_TEMP,SCHD_PUB_VCF,SCHD_PUB_DENS,SCHD_PRESETQTY,SCHD_DELIV_NUM,SCHD_SOLD_TO_NUM,SCHD_SHIP_TO_NUM,SCHD_ISOTAINER_NUM,SCHD_VISCOSITY,SCHD_MASS_ORG_SCHD,SCHD_MASS_ORG_PRELOAD,FASTTRACK_CALL_TIME,FASTTRACK_START_TIME,FASTTRACK_END_TIME,FASTTRACK_BAY) 
values (null,900001,'9998',4,'141','1',5,10000,0,null,null,43449135,4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null,null,null,null);
Insert into SPECDETS (SCHD_PMV_NUM,SCHDSPEC_SHLSTRIP,SCHDSPEC_SHLSSUPP,SCHD_COMP_ID,SCHDPROD_PRODCODE,SCHDPROD_PRODCMPY,SCHD_UNITS,SCHD_SPECQTY,SCHD_PRLDQTY,SCHD_ORDER,SCHD_SEAL_NUMBER,SCHD_TRAILER,SCHD_TRAILERCOMP,SCHD_FILLED,SCHD_TRSA_ID,SCHD_N_DRUMS,SCHD_DRUM_SZ,SCHD_DENSITY,SCHD_DELIVERED,SCHD_RPT_TEMP,SCHD_RPT_CFACTOR,SCHD_RPT_T_UNIT,SCHD_C_OF_E,SCHD_MASS_FRCTN,SCHD_HOST_DATA,ARMCODE,SCHD_TC_TODO,SCHD_PUB_TEMP,SCHD_PUB_VCF,SCHD_PUB_DENS,SCHD_PRESETQTY,SCHD_DELIV_NUM,SCHD_SOLD_TO_NUM,SCHD_SHIP_TO_NUM,SCHD_ISOTAINER_NUM,SCHD_VISCOSITY,SCHD_MASS_ORG_SCHD,SCHD_MASS_ORG_PRELOAD,FASTTRACK_CALL_TIME,FASTTRACK_START_TIME,FASTTRACK_END_TIME,FASTTRACK_BAY) 
values (null,900001,'9998',5,'141','1',5,10000,0,null,null,43449135,5,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null,null,null,null);
Insert into SPECDETS (SCHD_PMV_NUM,SCHDSPEC_SHLSTRIP,SCHDSPEC_SHLSSUPP,SCHD_COMP_ID,SCHDPROD_PRODCODE,SCHDPROD_PRODCMPY,SCHD_UNITS,SCHD_SPECQTY,SCHD_PRLDQTY,SCHD_ORDER,SCHD_SEAL_NUMBER,SCHD_TRAILER,SCHD_TRAILERCOMP,SCHD_FILLED,SCHD_TRSA_ID,SCHD_N_DRUMS,SCHD_DRUM_SZ,SCHD_DENSITY,SCHD_DELIVERED,SCHD_RPT_TEMP,SCHD_RPT_CFACTOR,SCHD_RPT_T_UNIT,SCHD_C_OF_E,SCHD_MASS_FRCTN,SCHD_HOST_DATA,ARMCODE,SCHD_TC_TODO,SCHD_PUB_TEMP,SCHD_PUB_VCF,SCHD_PUB_DENS,SCHD_PRESETQTY,SCHD_DELIV_NUM,SCHD_SOLD_TO_NUM,SCHD_SHIP_TO_NUM,SCHD_ISOTAINER_NUM,SCHD_VISCOSITY,SCHD_MASS_ORG_SCHD,SCHD_MASS_ORG_PRELOAD,FASTTRACK_CALL_TIME,FASTTRACK_START_TIME,FASTTRACK_END_TIME,FASTTRACK_BAY) 
values (null,900001,'9998',6,'141A','1',5,10000,0,null,null,43449135,6,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null,null,null,null);
Insert into SPECDETS (SCHD_PMV_NUM,SCHDSPEC_SHLSTRIP,SCHDSPEC_SHLSSUPP,SCHD_COMP_ID,SCHDPROD_PRODCODE,SCHDPROD_PRODCMPY,SCHD_UNITS,SCHD_SPECQTY,SCHD_PRLDQTY,SCHD_ORDER,SCHD_SEAL_NUMBER,SCHD_TRAILER,SCHD_TRAILERCOMP,SCHD_FILLED,SCHD_TRSA_ID,SCHD_N_DRUMS,SCHD_DRUM_SZ,SCHD_DENSITY,SCHD_DELIVERED,SCHD_RPT_TEMP,SCHD_RPT_CFACTOR,SCHD_RPT_T_UNIT,SCHD_C_OF_E,SCHD_MASS_FRCTN,SCHD_HOST_DATA,ARMCODE,SCHD_TC_TODO,SCHD_PUB_TEMP,SCHD_PUB_VCF,SCHD_PUB_DENS,SCHD_PRESETQTY,SCHD_DELIV_NUM,SCHD_SOLD_TO_NUM,SCHD_SHIP_TO_NUM,SCHD_ISOTAINER_NUM,SCHD_VISCOSITY,SCHD_MASS_ORG_SCHD,SCHD_MASS_ORG_PRELOAD,FASTTRACK_CALL_TIME,FASTTRACK_START_TIME,FASTTRACK_END_TIME,FASTTRACK_BAY) 
values (null,900001,'9998',7,'141A','1',5,10000,0,null,null,43449135,7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null,null,null,null);


-- mockup SPECPROD for 9998 - Pickup Schedule Company

Insert into SPECPROD (SCHPSPID_SHLSTRIP,SCHPSPID_SHLSSUPP,SCHPPROD_PRODCODE,SCHPPROD_PRODCMPY,SCHP_UNITS,SCHP_SPECQTY,SCHP_ORDER,SCHP_3RD_REVERSED,SCHP_MASS_ORG_SCHD,SCHP_MASS_ORG_PRELOAD) 
values (900001,'9998','141','1',5,50000,null,0,null,null);
Insert into SPECPROD (SCHPSPID_SHLSTRIP,SCHPSPID_SHLSSUPP,SCHPPROD_PRODCODE,SCHPPROD_PRODCMPY,SCHP_UNITS,SCHP_SPECQTY,SCHP_ORDER,SCHP_3RD_REVERSED,SCHP_MASS_ORG_SCHD,SCHP_MASS_ORG_PRELOAD) 
values (900001,'9998','141A','1',5,20000,null,0,null,null);


-- now fill the new table PICKUP_SCHEDULE_SPECS

INSERT INTO PICKUP_SCHEDULE_SPECS
(
    PLSS_PICKUP_TRIP,
    PLSS_PICKUP_SUPP,
    PLSS_PICKUP_CMPT,
    PLSS_STAGED_TRIP,
    PLSS_STAGED_SUPP,
    PLSS_STAGED_CMPT,
    PLSS_STAGED_PRODCODE,
    PLSS_STAGED_PRODCMPY,
    PLSS_STAGED_UNITS,
    PLSS_STAGED_SPECQTY,
    PLSS_STAGED_PRLDQTY,
    PLSS_STAGED_ORDER,
    PLSS_STAGED_CUST,
    PLSS_STAGED_DELVLOC,
    PLSS_STAGED_LOADTYPE	            
) VALUES (
    900001,        -- PLSS_PICKUP_TRIP,
    '9998',        -- PLSS_PICKUP_SUPP,
    1,             -- PLSS_PICKUP_CMPT,
    834,        -- PLSS_STAGED_TRIP,
    '1',     -- PLSS_STAGED_SUPP,
    1,             -- PLSS_STAGED_CMPT,
    '141',   -- PLSS_STAGED_PRODCODE,
    '1',     -- PLSS_STAGED_PRODCMPY,
    5,             -- PLSS_STAGED_UNITS,
    10000,         -- PLSS_STAGED_SPECQTY,
    0,             -- PLSS_STAGED_PRLDQTY,
    NULL,          -- PLSS_STAGED_ORDER,
    '104',    -- PLSS_STAGED_CUST,
    '11',    -- PLSS_STAGED_DELVLOC,
    2              -- PLSS_STAGED_LOADTYPE	            
);

INSERT INTO PICKUP_SCHEDULE_SPECS
(
    PLSS_PICKUP_TRIP,
    PLSS_PICKUP_SUPP,
    PLSS_PICKUP_CMPT,
    PLSS_STAGED_TRIP,
    PLSS_STAGED_SUPP,
    PLSS_STAGED_CMPT,
    PLSS_STAGED_PRODCODE,
    PLSS_STAGED_PRODCMPY,
    PLSS_STAGED_UNITS,
    PLSS_STAGED_SPECQTY,
    PLSS_STAGED_PRLDQTY,
    PLSS_STAGED_ORDER,
    PLSS_STAGED_CUST,
    PLSS_STAGED_DELVLOC,
    PLSS_STAGED_LOADTYPE	            
) VALUES (
    900001,        -- PLSS_PICKUP_TRIP,
    '9998',        -- PLSS_PICKUP_SUPP,
    2,             -- PLSS_PICKUP_CMPT,
    834,        -- PLSS_STAGED_TRIP,
    '1',     -- PLSS_STAGED_SUPP,
    2,             -- PLSS_STAGED_CMPT,
    '141',   -- PLSS_STAGED_PRODCODE,
    '1',     -- PLSS_STAGED_PRODCMPY,
    5,             -- PLSS_STAGED_UNITS,
    10000,         -- PLSS_STAGED_SPECQTY,
    0,             -- PLSS_STAGED_PRLDQTY,
    NULL,          -- PLSS_STAGED_ORDER,
    '104',    -- PLSS_STAGED_CUST,
    '11',    -- PLSS_STAGED_DELVLOC,
    2              -- PLSS_STAGED_LOADTYPE	            
);

INSERT INTO PICKUP_SCHEDULE_SPECS
(
    PLSS_PICKUP_TRIP,
    PLSS_PICKUP_SUPP,
    PLSS_PICKUP_CMPT,
    PLSS_STAGED_TRIP,
    PLSS_STAGED_SUPP,
    PLSS_STAGED_CMPT,
    PLSS_STAGED_PRODCODE,
    PLSS_STAGED_PRODCMPY,
    PLSS_STAGED_UNITS,
    PLSS_STAGED_SPECQTY,
    PLSS_STAGED_PRLDQTY,
    PLSS_STAGED_ORDER,
    PLSS_STAGED_CUST,
    PLSS_STAGED_DELVLOC,
    PLSS_STAGED_LOADTYPE	            
) VALUES (
    900001,        -- PLSS_PICKUP_TRIP,
    '9998',        -- PLSS_PICKUP_SUPP,
    3,             -- PLSS_PICKUP_CMPT,
    835,        -- PLSS_STAGED_TRIP,
    '1',     -- PLSS_STAGED_SUPP,
    3,             -- PLSS_STAGED_CMPT,
    '141',   -- PLSS_STAGED_PRODCODE,
    '1',     -- PLSS_STAGED_PRODCMPY,
    5,             -- PLSS_STAGED_UNITS,
    10000,         -- PLSS_STAGED_SPECQTY,
    0,             -- PLSS_STAGED_PRLDQTY,
    NULL,          -- PLSS_STAGED_ORDER,
    '104',    -- PLSS_STAGED_CUST,
    '11',    -- PLSS_STAGED_DELVLOC,
    2              -- PLSS_STAGED_LOADTYPE	            
);

INSERT INTO PICKUP_SCHEDULE_SPECS
(
    PLSS_PICKUP_TRIP,
    PLSS_PICKUP_SUPP,
    PLSS_PICKUP_CMPT,
    PLSS_STAGED_TRIP,
    PLSS_STAGED_SUPP,
    PLSS_STAGED_CMPT,
    PLSS_STAGED_PRODCODE,
    PLSS_STAGED_PRODCMPY,
    PLSS_STAGED_UNITS,
    PLSS_STAGED_SPECQTY,
    PLSS_STAGED_PRLDQTY,
    PLSS_STAGED_ORDER,
    PLSS_STAGED_CUST,
    PLSS_STAGED_DELVLOC,
    PLSS_STAGED_LOADTYPE	            
) VALUES (
    900001,        -- PLSS_PICKUP_TRIP,
    '9998',        -- PLSS_PICKUP_SUPP,
    4,             -- PLSS_PICKUP_CMPT,
    835,        -- PLSS_STAGED_TRIP,
    '1',     -- PLSS_STAGED_SUPP,
    4,             -- PLSS_STAGED_CMPT,
    '141',   -- PLSS_STAGED_PRODCODE,
    '1',     -- PLSS_STAGED_PRODCMPY,
    5,             -- PLSS_STAGED_UNITS,
    10000,         -- PLSS_STAGED_SPECQTY,
    0,             -- PLSS_STAGED_PRLDQTY,
    NULL,          -- PLSS_STAGED_ORDER,
    '104',    -- PLSS_STAGED_CUST,
    '11',    -- PLSS_STAGED_DELVLOC,
    2              -- PLSS_STAGED_LOADTYPE	            
);

INSERT INTO PICKUP_SCHEDULE_SPECS
(
    PLSS_PICKUP_TRIP,
    PLSS_PICKUP_SUPP,
    PLSS_PICKUP_CMPT,
    PLSS_STAGED_TRIP,
    PLSS_STAGED_SUPP,
    PLSS_STAGED_CMPT,
    PLSS_STAGED_PRODCODE,
    PLSS_STAGED_PRODCMPY,
    PLSS_STAGED_UNITS,
    PLSS_STAGED_SPECQTY,
    PLSS_STAGED_PRLDQTY,
    PLSS_STAGED_ORDER,
    PLSS_STAGED_CUST,
    PLSS_STAGED_DELVLOC,
    PLSS_STAGED_LOADTYPE	            
) VALUES (
    900001,        -- PLSS_PICKUP_TRIP,
    '9998',        -- PLSS_PICKUP_SUPP,
    5,             -- PLSS_PICKUP_CMPT,
    836,        -- PLSS_STAGED_TRIP,
    '1',     -- PLSS_STAGED_SUPP,
    NULL,             -- PLSS_STAGED_CMPT,
    '141',   -- PLSS_STAGED_PRODCODE,
    '1',     -- PLSS_STAGED_PRODCMPY,
    5,             -- PLSS_STAGED_UNITS,
    10000,         -- PLSS_STAGED_SPECQTY,
    0,             -- PLSS_STAGED_PRLDQTY,
    NULL,          -- PLSS_STAGED_ORDER,
    '104',    -- PLSS_STAGED_CUST,
    '11',    -- PLSS_STAGED_DELVLOC,
    3              -- PLSS_STAGED_LOADTYPE	            
);

INSERT INTO PICKUP_SCHEDULE_SPECS
(
    PLSS_PICKUP_TRIP,
    PLSS_PICKUP_SUPP,
    PLSS_PICKUP_CMPT,
    PLSS_STAGED_TRIP,
    PLSS_STAGED_SUPP,
    PLSS_STAGED_CMPT,
    PLSS_STAGED_PRODCODE,
    PLSS_STAGED_PRODCMPY,
    PLSS_STAGED_UNITS,
    PLSS_STAGED_SPECQTY,
    PLSS_STAGED_PRLDQTY,
    PLSS_STAGED_ORDER,
    PLSS_STAGED_CUST,
    PLSS_STAGED_DELVLOC,
    PLSS_STAGED_LOADTYPE	            
) VALUES (
    900001,        -- PLSS_PICKUP_TRIP,
    '9998',        -- PLSS_PICKUP_SUPP,
    6,             -- PLSS_PICKUP_CMPT,
    836,        -- PLSS_STAGED_TRIP,
    '1',     -- PLSS_STAGED_SUPP,
    NULL,             -- PLSS_STAGED_CMPT,
    '141A',   -- PLSS_STAGED_PRODCODE,
    '1',     -- PLSS_STAGED_PRODCMPY,
    5,             -- PLSS_STAGED_UNITS,
    10000,         -- PLSS_STAGED_SPECQTY,
    0,             -- PLSS_STAGED_PRLDQTY,
    NULL,          -- PLSS_STAGED_ORDER,
    '104',    -- PLSS_STAGED_CUST,
    '11',    -- PLSS_STAGED_DELVLOC,
    3              -- PLSS_STAGED_LOADTYPE	            
);

INSERT INTO PICKUP_SCHEDULE_SPECS
(
    PLSS_PICKUP_TRIP,
    PLSS_PICKUP_SUPP,
    PLSS_PICKUP_CMPT,
    PLSS_STAGED_TRIP,
    PLSS_STAGED_SUPP,
    PLSS_STAGED_CMPT,
    PLSS_STAGED_PRODCODE,
    PLSS_STAGED_PRODCMPY,
    PLSS_STAGED_UNITS,
    PLSS_STAGED_SPECQTY,
    PLSS_STAGED_PRLDQTY,
    PLSS_STAGED_ORDER,
    PLSS_STAGED_CUST,
    PLSS_STAGED_DELVLOC,
    PLSS_STAGED_LOADTYPE	            
) VALUES (
    900001,        -- PLSS_PICKUP_TRIP,
    '9998',        -- PLSS_PICKUP_SUPP,
    7,             -- PLSS_PICKUP_CMPT,
    836,        -- PLSS_STAGED_TRIP,
    '1',     -- PLSS_STAGED_SUPP,
    NULL,             -- PLSS_STAGED_CMPT,
    '141A',   -- PLSS_STAGED_PRODCODE,
    '1',     -- PLSS_STAGED_PRODCMPY,
    5,             -- PLSS_STAGED_UNITS,
    10000,         -- PLSS_STAGED_SPECQTY,
    0,             -- PLSS_STAGED_PRLDQTY,
    NULL,          -- PLSS_STAGED_ORDER,
    '104',    -- PLSS_STAGED_CUST,
    '11',    -- PLSS_STAGED_DELVLOC,
    3              -- PLSS_STAGED_LOADTYPE	            
);




-- now change the SHLS_PICKUP_MODE in 900126 ~ 900128
update schedule set shls_pickup_mode=2 where shls_trip_no in (834, 835, 836) and shls_supp='1';

commit;

/*
-- reverse
update schedule set shls_pickup_mode=0 where shls_trip_no in (834, 835, 836) and shls_supp='1';
delete from PICKUP_SCHEDULE_SPECS where PLSS_PICKUP_TRIP=900001 and PLSS_PICKUP_SUPP='9998';
delete from SPECPROD where SCHPSPID_SHLSTRIP=900001 and SCHPSPID_SHLSSUPP='9998';
delete from SPECDETS where SCHDSPEC_SHLSTRIP=900001 and SCHDSPEC_SHLSSUPP='9998';
delete from SCHEDULE where SHLS_TRIP_NO=900001 and SHLS_SUPP='9998';
commit;
*/