CREATE OR REPLACE FORCE VIEW PICKUP_SCHEDULE_SPECS_VW  AS 
SELECT * 
FROM (
    SELECT PLSS.*, CMPT.SCHD_SPECQTY AS PLSS_STAGED_AVAILQTY, SCHD.SHLS_LD_TYPE AS PLSS_STAGED_LOADTYPE2, 0 AS PLSS_STAGED_AVAILORD
    FROM PICKUP_SCHEDULE_SPECS PLSS, SPECDETS CMPT, SCHEDULE SCHD
    WHERE
        PLSS.PLSS_STAGED_TRIP = CMPT.SCHDSPEC_SHLSTRIP
        AND PLSS.PLSS_STAGED_SUPP = CMPT.SCHDSPEC_SHLSSUPP
        AND PLSS.PLSS_STAGED_CMPT = CMPT.SCHD_COMP_ID
        AND PLSS.PLSS_STAGED_PRODCODE = CMPT.SCHDPROD_PRODCODE
        AND PLSS.PLSS_STAGED_PRODCMPY = CMPT.SCHDPROD_PRODCMPY
        AND PLSS.PLSS_STAGED_ORDER IS NULL
        AND SCHD.SHLS_TRIP_NO = CMPT.SCHDSPEC_SHLSTRIP
        AND SCHD.SHLS_SUPP = CMPT.SCHDSPEC_SHLSSUPP
        AND SCHD.SHLS_LD_TYPE = 2
    UNION ALL
    SELECT PLSS.*, PROD.SCHP_SPECQTY AS PLSS_STAGED_AVAILQTY, SCHD.SHLS_LD_TYPE AS PLSS_STAGED_LOADTYPE2, 0 AS PLSS_STAGED_AVAILORD
    FROM PICKUP_SCHEDULE_SPECS PLSS, SPECPROD PROD, SCHEDULE SCHD
    WHERE
        PLSS.PLSS_STAGED_TRIP = PROD.SCHPSPID_SHLSTRIP
        AND PLSS.PLSS_STAGED_SUPP = PROD.SCHPSPID_SHLSSUPP
        AND PLSS.PLSS_STAGED_PRODCODE = PROD.SCHPPROD_PRODCODE
        AND PLSS.PLSS_STAGED_PRODCMPY = PROD.SCHPPROD_PRODCMPY
        AND PLSS.PLSS_STAGED_CMPT IS NULL
        AND PLSS.PLSS_STAGED_ORDER IS NULL
        AND SCHD.SHLS_TRIP_NO = PROD.SCHPSPID_SHLSTRIP
        AND SCHD.SHLS_SUPP = PROD.SCHPSPID_SHLSSUPP
        AND SCHD.SHLS_LD_TYPE = 3
    UNION ALL
    SELECT PLSS.*, PROD.SCHP_SPECQTY AS PLSS_STAGED_AVAILQTY, SCHD.SHLS_LD_TYPE AS PLSS_STAGED_LOADTYPE2, (OPRD.ORDER_PROD_QTY - OPRD.OPROD_SCHEDULED) AS PLSS_STAGED_AVAILORD
    FROM PICKUP_SCHEDULE_SPECS PLSS, SPECPROD PROD, SCHEDULE SCHD, OPRODMTD OPRD
    WHERE
        PLSS.PLSS_STAGED_TRIP = PROD.SCHPSPID_SHLSTRIP
        AND PLSS.PLSS_STAGED_SUPP = PROD.SCHPSPID_SHLSSUPP
        AND PLSS.PLSS_STAGED_PRODCODE = PROD.SCHPPROD_PRODCODE
        AND PLSS.PLSS_STAGED_PRODCMPY = PROD.SCHPPROD_PRODCMPY
        AND PLSS.PLSS_STAGED_CMPT IS NULL
        AND PLSS.PLSS_STAGED_ORDER = PROD.SCHP_ORDER
        AND SCHD.SHLS_TRIP_NO = PROD.SCHPSPID_SHLSTRIP
        AND SCHD.SHLS_SUPP = PROD.SCHPSPID_SHLSSUPP
        AND SCHD.SHLS_LD_TYPE = 4
        AND PLSS.PLSS_STAGED_PRODCODE = OPRD.OSPROD_PRODCODE
        AND PLSS.PLSS_STAGED_PRODCMPY = OPRD.OSPROD_PRODCMPY
        AND PLSS.PLSS_STAGED_ORDER = OPRD.ORDER_PROD_KEY
);

/

commit;



/*
SELECT * 
FROM (
    SELECT PLSS.*, CMPT.SCHD_SPECQTY AS PLSS_STAGED_AVAILQTY
    FROM PICKUP_SCHEDULE_SPECS PLSS, SPECDETS CMPT
    WHERE
        PLSS.PLSS_STAGED_TRIP = CMPT.SCHDSPEC_SHLSTRIP
        AND PLSS.PLSS_STAGED_SUPP = CMPT.SCHDSPEC_SHLSSUPP
        AND PLSS.PLSS_STAGED_CMPT = CMPT.SCHD_COMP_ID
        AND PLSS.PLSS_STAGED_PRODCODE = CMPT.SCHDPROD_PRODCODE
        AND PLSS.PLSS_STAGED_PRODCMPY = CMPT.SCHDPROD_PRODCMPY
        AND PLSS.PLSS_STAGED_ORDER IS NULL
    UNION ALL
    SELECT PLSS.*, PROD.SCHP_SPECQTY AS PLSS_STAGED_AVAILQTY
    FROM PICKUP_SCHEDULE_SPECS PLSS, SPECPROD PROD
    WHERE
        PLSS.PLSS_STAGED_TRIP = PROD.SCHPSPID_SHLSTRIP
        AND PLSS.PLSS_STAGED_SUPP = PROD.SCHPSPID_SHLSSUPP
        AND PLSS.PLSS_STAGED_PRODCODE = PROD.SCHPPROD_PRODCODE
        AND PLSS.PLSS_STAGED_PRODCMPY = PROD.SCHPPROD_PRODCMPY
        AND PLSS.PLSS_STAGED_CMPT IS NULL
        AND PLSS.PLSS_STAGED_ORDER IS NULL
    UNION ALL
    SELECT PLSS.*, (OPRD.ORDER_PROD_QTY - OPRD.OPROD_SCHEDULED) AS PLSS_STAGED_AVAILQTY
    FROM PICKUP_SCHEDULE_SPECS PLSS, OPRODMTD OPRD
    WHERE
        PLSS.PLSS_STAGED_PRODCODE = OPRD.OSPROD_PRODCODE
        AND PLSS.PLSS_STAGED_PRODCMPY = OPRD.OSPROD_PRODCMPY
        AND PLSS.PLSS_STAGED_CMPT IS NULL
        AND PLSS.PLSS_STAGED_ORDER = OPRD.ORDER_PROD_KEY
);
*/
