/*
    Make default precisions and maximum lengths editable in GUI
*/

UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_DEFAULT_PRECISION_ADDITIVE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_DEFAULT_PRECISION_API';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_DEFAULT_PRECISION_DENSITY';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_DEFAULT_PRECISION_LEVEL';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_DEFAULT_PRECISION_MASS';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_DEFAULT_PRECISION_SG';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_DEFAULT_PRECISION_TEMPERATURE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_DEFAULT_PRECISION_VOLUME';

UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_BASECODE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_CMPYCODE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_CUSTACCT';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_EMAIL';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_EQPTCODE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_ORDREFCODE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_PRODCODE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_PSNLCODE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_SLP';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_TANKCODE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'L' WHERE CONFIG_KEY = 'SITE_MAXLEN_TNKRCODE';

COMMIT;