/*
-- existing definitions
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3070,'CHN','未知来源');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3070,'ENG','Unknown source');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3071,'CHN','本地手工生成');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3071,'ENG','Created manually');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3072,'CHN','远程系统生成');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3072,'ENG','Received from host');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3073,'CHN','来自开放订单');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3073,'ENG','Generated by open order');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3074,'CHN','本地系统生成');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3074,'ENG','Generated by system');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3075,'CHN','独立发油或特殊货单');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3075,'ENG','Standalone or Special');

insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 0, 'U', 3070);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 1, 'M', 3071);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 2, 'H', 3072);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 3, 'O', 3073);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 4, 'S', 3074);
*/

delete from MSG_LOOKUP where MSG_ID IN (3075, 3076);

commit;

Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3075,'CHN','独立发油生成');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3075,'ENG','Generated by Standalone');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3076,'CHN','特殊发油生成');
Insert into MSG_LOOKUP (MSG_ID,LANG_ID,MESSAGE) values (3076,'ENG','Generated by Special Load');

commit;


delete from ENUMITEM where ENUMTYPENAME='SHL_SOURCE_TYPE';

commit;

insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 0, 'U', 3070);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 1, 'M', 3071);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 2, 'H', 3072);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 3, 'O', 3073);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 4, 'S', 3074);

insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 5, 'A', 3075);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SHL_SOURCE_TYPE', 6, 'L', 3076);

commit;
