/*
    Make WRI related settings editable in GUI
*/

UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'W' WHERE CONFIG_KEY = 'WRI_ENABLE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'W' WHERE CONFIG_KEY = 'WRI_EXPIRY_DAYS';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'W' WHERE CONFIG_KEY = 'WRI_PARTIAL_MATCH';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'W' WHERE CONFIG_KEY = 'SITE_USE_LONG_VEHICLE';

COMMIT;