/*
    Make staging bay related settings editable in GUI
*/

UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'B' WHERE CONFIG_KEY = 'SITE_USE_STAGING_BAY';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'B' WHERE CONFIG_KEY = 'SITE_CMPY_LOAD_OPTIONS_DEFAULT';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'B' WHERE CONFIG_KEY = 'SITE_CMPY_LOAD_OPTIONS_EDITABLE';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'B' WHERE CONFIG_KEY = 'SITE_PICKUP_TRIP_START';
UPDATE SITE_CONFIG SET CONFIG_REQUIRED_BY_GUI = 'B' WHERE CONFIG_KEY = 'SITE_PICKUP_TRIP_END';

COMMIT;