
UPDATE PRODUCTS SET PROD_IS_BLEND='Y' 
WHERE (PROD_CODE, PROD_CMPY) IN (
	SELECT PROD_CODE, PROD_CMPY FROM (
		SELECT PROD_CODE, PROD_CMPY, PROD_IS_BLEND, COUNT(BASE_CODE) AS BASE_COUNT
		FROM RPTOBJ_PROD_DETAILS_VW WHERE BASE_CLASS_NO != 6 AND BASE_CLASS_NO != 11 GROUP BY PROD_CODE, PROD_CMPY, PROD_IS_BLEND
	) WHERE BASE_COUNT > 1
);

UPDATE PRODUCTS SET PROD_IS_BLEND='N' 
WHERE (PROD_CODE, PROD_CMPY) IN (
	SELECT PROD_CODE, PROD_CMPY FROM (
		SELECT PROD_CODE, PROD_CMPY, PROD_IS_BLEND, COUNT(BASE_CODE) AS BASE_COUNT
		FROM RPTOBJ_PROD_DETAILS_VW WHERE BASE_CLASS_NO != 6 AND BASE_CLASS_NO != 11 GROUP BY PROD_CODE, PROD_CMPY, PROD_IS_BLEND
	) WHERE BASE_COUNT = 1
);


/*
-- use the following scripts to check the result
SELECT * FROM (
	SELECT PROD_CODE, PROD_CMPY, PROD_IS_BLEND, COUNT(BASE_CODE) AS BASE_COUNT
	FROM RPTOBJ_PROD_DETAILS_VW WHERE BASE_CLASS_NO != 6 AND BASE_CLASS_NO != 11 GROUP BY PROD_CODE, PROD_CMPY, PROD_IS_BLEND
) WHERE BASE_COUNT > 1;


SELECT * FROM (
	SELECT PROD_CODE, PROD_CMPY, PROD_IS_BLEND, COUNT(BASE_CODE) AS BASE_COUNT
	FROM RPTOBJ_PROD_DETAILS_VW WHERE BASE_CLASS_NO != 6 AND BASE_CLASS_NO != 11 GROUP BY PROD_CODE, PROD_CMPY, PROD_IS_BLEND
) WHERE BASE_COUNT = 1;

SELECT * FROM (
SELECT PROD_CODE, PROD_CMPY, PROD_IS_BLEND, ADTV_FLAG, COUNT(BASE_CODE) AS BASE_COUNT
FROM (
	SELECT PROD_CODE, PROD_CMPY, PROD_IS_BLEND, BASE_CODE, BASE_NAME, (CASE WHEN BASE_CLASS_NO != 6 AND BASE_CLASS_NO != 11 THEN 0 ELSE 1 END) AS ADTV_FLAG
	FROM RPTOBJ_PROD_DETAILS_VW
)
GROUP BY PROD_CODE, PROD_CMPY, PROD_IS_BLEND, ADTV_FLAG
) WHERE ADTV_FLAG=0;
*/