/*
Wrong definition on GE server
0	CONTRACTOR	509
1	MANAGER	500
2	ACCOUNTANT	501
3	SUPERVISOR	502
4	ENGINEER	503
5	DISPATCHER	504
6	GUARD	505
7	 	506
8	DRIVER	507
9	TEST_LOADER	508
*/

UPDATE MSG_LOOKUP SET MESSAGE='DRIVER' WHERE LANG_ID='ENG' AND MSG_ID=506;
UPDATE MSG_LOOKUP SET MESSAGE='CONTRACTOR' WHERE LANG_ID='ENG' AND MSG_ID=507;
UPDATE MSG_LOOKUP SET MESSAGE='LOADER' WHERE LANG_ID='ENG' AND MSG_ID=508;
UPDATE MSG_LOOKUP SET MESSAGE='VISITOR' WHERE LANG_ID='ENG' AND MSG_ID=509;

COMMIT;

/*
SELECT cmsg.*, emsg.*
FROM (
            SELECT LANG_ID, ENUMITEM.ENUM_NO AS ROLE_ID, MSG_LOOKUP.MESSAGE AS ROLE_NAME, MSG_LOOKUP.MSG_ID
            FROM ENUMITEM, MSG_LOOKUP
            WHERE ENUMITEM.ENUM_TMM = MSG_LOOKUP.MSG_ID AND ENUMTYPENAME = 'AUTH_LEVEL' AND LANG_ID='ENG'
) emsg, (
            SELECT LANG_ID, ENUMITEM.ENUM_NO AS ROLE_ID, MSG_LOOKUP.MESSAGE AS ROLE_NAME, MSG_LOOKUP.MSG_ID
            FROM ENUMITEM, MSG_LOOKUP
            WHERE ENUMITEM.ENUM_TMM = MSG_LOOKUP.MSG_ID AND ENUMTYPENAME = 'AUTH_LEVEL' AND LANG_ID='CHN'
) cmsg
WHERE emsg.ROLE_ID = cmsg.ROLE_ID
;
*/
