const columns = (t) => [
  {
    headerName: t('fields.orderSysNo'),
    field: 'order_sys_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderSuppCode'),
    field: 'order_supp_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderSuppName'),
    field: 'order_supp_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderCustAcnt'),
    field: 'order_cust_acnt',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderCustCode'),
    field: 'order_cust_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderCustName'),
    field: 'order_cust_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderCustNo'),
    field: 'order_cust_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderStatId'),
    field: 'order_stat_id',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderStatName'),
    field: 'order_stat_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderOrdTime'),
    field: 'order_ord_time',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 130,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.orderExpTime'),
    field: 'order_exp_time',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 130,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.orderModifiedOn'),
    field: 'order_last_change',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 130,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.orderDlocCode'),
    field: 'order_dloc_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.orderDlocName'),
    field: 'order_dloc_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.orderRefCode'),
    field: 'order_ref_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.orderDlvTime'),
    field: 'order_dlv_time',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.orderDrwrCode'),
    field: 'order_drwr_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.orderDrwrName'),
    field: 'order_drwr_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
  },
  
  {
    headerName: t('fields.orderCarrCode'),
    field: 'order_carr_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.orderCarrName'),
    field: 'order_carr_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.orderApproved'),
    field: 'order_approved',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 80,
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.orderAppNo'),
    field: 'order_app_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.orderAppTime'),
    field: 'order_app_time',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
    cellRenderer: 'DateRenderer',
    hide: true,
  },
  {
    headerName: t('fields.orderPsnlCode'),
    field: 'order_psnl_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.orderPsnlName'),
    field: 'order_psnl_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.orderSoldToTitle'),
    field: 'order_sold_to_num',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.orderShipToTitle'),
    field: 'order_ship_to_num',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
  },

  {
    headerName: t('fields.orderTtypId'),
    field: 'order_ttyp_id',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderTtypName'),
    field: 'order_ttyp_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderStypId'),
    field: 'order_styp_id',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderStypName'),
    field: 'order_styp_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderDtrmCode'),
    field: 'order_dtrm_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderDtrmName'),
    field: 'order_dtrm_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderInvNo'),
    field: 'order_inv_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderTotal'),
    field: 'order_total',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderLimit'),
    field: 'order_limit',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderTrsfType'),
    field: 'order_trsf_type',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderPricePrinted'),
    field: 'order_price_printed',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    width: 80,
    cellRenderer: "BooleanRenderer",
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderStrmCode'),
    field: 'order_strm_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderStrmName'),
    field: 'order_strm_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderPayNote'),
    field: 'order_pay_note',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderSrcId'),
    field: 'order_src_id',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderSrcName'),
    field: 'order_src_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.orderItems'),
    field: 'order_items',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
];

export default columns;
