<?php
function getBayviewServerConfiguration()
{
	// shellWPI
	$bayviewBayServers=array(
		'BAY001'=>array(
			'bay_code'=>'BAY001', 
			'cfg_file'=>'data_config4bay1.json', 
			'server_url'=>'http://localhost:3001/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY002'=>array(
			'bay_code'=>'BAY002', 
			'cfg_file'=>'data_config4bay2.json', 
			'server_url'=>'http://localhost:3002/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY003'=>array(
			'bay_code'=>'BAY003', 
			'cfg_file'=>'data_config4bay3.json', 
			'server_url'=>'http://localhost:3003/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY004'=>array(
			'bay_code'=>'BAY004', 
			'cfg_file'=>'data_config4bay4.json', 
			'server_url'=>'http://localhost:3004/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>false
		),
		'BAY05L'=>array(
			'bay_code'=>'BAY05L', 
			'cfg_file'=>'data_config4bay5L.json', 
			'server_url'=>'http://localhost:3005/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY05R'=>array(
			'bay_code'=>'BAY05R', 
			'cfg_file'=>'data_config4bay5R.json', 
			'server_url'=>'http://localhost:3015/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		),
		'BAY006'=>array(
			'bay_code'=>'BAY006', 
			'cfg_file'=>'data_config4bay6.json', 
			'server_url'=>'http://localhost:3006/point_data/', 
			'bay_unit'=>5,
			'action'=>1,
			'active'=>true
		)
	);
	
	return $bayviewBayServers;
}
?>
