const columns = (t, pageState, form) => [
  {
    headerName: `${t('fields.addressAction')}`,
    field: 'ddi_addl_action',
    width: 32,
    //checkboxSelection: true,
    cellRenderer: 'MarkRenderer',
    suppressSizeToFit: true,
    pinned: 'left',
    hide: true,
  },
  {
    headerName: t('fields.ddiDdNumber'),
    field: 'ddi_dd_number',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 150,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.ddiDdSuppCode'),
    field: 'ddi_dd_supp_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.ddiDdSuppName'),
    field: 'ddi_dd_supp_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 150,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.ddiDdTripOrdNo'),
    field: 'ddi_dd_tripord_no',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.ddiDdLdType'),
    field: 'ddi_dd_ld_type',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.ddiDdLoadTypeName'),
    field: 'ddi_dd_load_typename',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.ddiLineItemNum'),
    field: 'ddi_line_item_num',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 150,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.ddiAddiFldLineNo'),
    field: 'addi_fld_line_no',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 200,
    // suppressSizeToFit: true,
  },
  {
    headerName: t('fields.ddiAddiFldInfo'),
    field: 'addi_fld_info',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: true,
    width: 400,
    // suppressSizeToFit: true,
  },
  {
    headerName: '',
    field: 'idle_cln',
    width: 10,
    hide: false,
  },
];

export default columns;
