export const TRIPS = '/api/pages/manual_trans/get_trips.php';
export const CARRIER_AND_TANKER = '/api/pages/manual_trans/get_sched_basics.php';
export const DRIVERS = '/api/pages/manual_trans/get_drivers.php';
export const DETAILS = '/api/pages/manual_trans/get_sched_details.php';
export const GET_ARMS = '/api/pages/manual_trans/get_arms.php';
export const BASE_DETAILS = '/api/pages/manual_trans/get_base_details.php';
export const PRODUCTS = '/api/pages/schedule/get_product_details.php';
export const SUPPLIERS = '/api/pages/manual_trans/get_suppliers.php';
export const CUSTOMERS = '/api/pages/manual_trans/get_customers.php';
export const ORDERS = '/api/pages/manual_trans/get_orders.php';
export const CARRIERS = '/api/pages/manual_trans/carriers.php';
export const TANKERS = '/api/pages/manual_trans/tankers_by_carrier.php';
export const ORDER_DETAILS = '/api/pages/manual_trans/get_order_details.php';
export const ORDER_SUPPLIERS = '/api/pages/manual_trans/get_ord_suppliers.php';
export const SCHEDULE_SUPPLIERS = '/api/pages/manual_trans/get_schd_suppliers.php';

export const CALCULATE = '/api/pages/manual_trans/calc_vcf.php';
export const SUBMIT = '/api/pages/manual_trans/submit.php';
export const SAVE = '/api/pages/manual_trans/save.php ';
