const columns = (t, pageState, form, units) => [
  {
    headerName: t('fields.oprdOrderId'),
    field: 'oprd_order_id',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.orderSuppCode'),
    field: 'oprd_supp_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderSuppName'),
    field: 'oprd_supp_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false, 
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderCustAcnt'),
    field: 'oprd_cust_acnt',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderCustCode'),
    field: 'oprd_cust_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderCustName'),
    field: 'oprd_cust_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderCustNo'),
    field: 'oprd_cust_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderStatId'),
    field: 'oprd_stat_id',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderStatName'),
    field: 'oprd_stat_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 160,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.orderApproved'),
    field: 'oprd_approved',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    suppressSizeToFit: true,
    width: 80,
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.orderOrdTime'),
    field: 'oprd_ord_time',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 130,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.orderExpTime'),
    field: 'oprd_exp_time',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 130,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  
  {
    headerName: t('fields.oprdProdCode'),
    field: 'oprd_prod_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    editable: false,
    width: 100,
    //cellRenderer: 'ProductRender',
  },
  {
    headerName: t('fields.oprdProdName'),
    field: 'oprd_prod_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
  },
  {
    headerName: t('fields.oprdProdCmpy'),
    field: 'oprd_prod_cmpy',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.oprdDrwrName'),
    field: 'oprd_drwr_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
  },
  {
    headerName: t('fields.oprdPeriodNo'),
    field: 'oprd_period_no',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.oprdPeriodStart'),
    field: 'oprd_period_start',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 130,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.oprdPeriodEnd'),
    field: 'oprd_period_end',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 130,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.oprdProdUnit'),
    field: 'oprd_prod_unit',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    cellEditor: 'UnitEditor',
    width: 130,
    cellEditorParams: {
      values: units?.records,
      form: form,
    },
  },
  {
    headerName: t('fields.oprdUnitName'),
    field: 'oprd_unit_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 80,
  },
  {
    headerName: t('fields.oprdProdQty'),
    field: 'oprd_prod_qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.oprdProdUsed'),
    field: 'oprd_prod_used',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.oprdPriceFixed'),
    field: 'oprd_price_fixed',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    suppressSizeToFit: true,
    width: 80,
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.oprdProdPrice'),
    field: 'oprd_prod_price',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
  },
];

export default columns;
