const columns = (t) => [
  {
    headerName: t('fields.partnerId'),
    field: 'prtnr_seq',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 100,
  },
  {
    headerName: t('fields.companyCode'),
    field: 'prtnr_cmpy',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 150,
  },
  {
    headerName: t('fields.companyName'),
    field: 'prtnr_cmpy_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 150,
  },
  {
    headerName: t('fields.partnerCode'),
    field: 'prtnr_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 130,
  },
  {
    headerName: t('fields.partnerName'),
    field: 'prtnr_name1',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 150,
  },

  {
    headerName: `${t('fields.partnerName')} 2`,
    field: 'prtnr_name2',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 140,
  },
  {
    headerName: `${t('fields.partnerName')} 3`,
    field: 'prtnr_name3',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 140,
  },
  {
    headerName: `${t('fields.partnerName')} 4`,
    field: 'prtnr_name4',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 140,
  },
  {
    headerName: `${t('fields.partnerName')} 5`,
    field: 'prtnr_name5',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 140,
  },
  {
    headerName: t('fields.partnerTypeCode'),
    field: 'prtnr_type',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 150,
  },
  {
    headerName: `${t('fields.partnerType')}`,
    field: 'prtnr_type_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 130,
  },
  {
    headerName: t('fields.partnerAddressCode'),
    field: 'prtnr_addr_text',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 180,
  },

  {
    headerName: t('fields.partnerAddress'),
    field: 'prtnr_desc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 160,
  },
  {
    headerName: t('fields.countPartnerPartnership'),
    field: 'pshp_count',
    filterable: true,
    sortable: true,
    resizable: true,
    width: 140,
    // hide: true,
  },
];

export default columns;
