const columns = (t, pageState, form, arm) => [
  {
    headerName: t('fields.nomtranBaseGui'),
    field: 'trsf_bs_prodcd',
    //field: 'trsb_bs',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
  {
    headerName: t('fields.nomtranTankCode'),
    field: 'trsf_bs_tk_cd',
    //field: 'trsb_tk_tankcode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
  {
    headerName: t('fields.nomtranBclassDesc'),
    field: 'trsf_bs_prodcls',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
  {
    headerName: t('fields.nomtranTankDens'),
    field: 'trsf_bs_den',
    //field: 'trsb_dns',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: ((pageState==='disposal' && !!arm)? true : false),
  },
  {
    headerName: t('fields.nomtranTemperature'),
    field: 'trsf_bs_temp',
    //field: 'trsb_tmp',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: false,
  },
  {
    headerName: t('fields.nomtranAmbVol'),
    field: 'trsf_bs_qty_amb',
    //field: 'trsb_avl',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: ((pageState==='disposal' && !!arm)? true : false),
  },
  {
    headerName: t('fields.nomtranCorVol'),
    field: 'trsf_bs_qty_cor',
    //field: 'trsb_cvl',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: ((pageState==='disposal' && !!arm)? true : false),
  },
  {
    headerName: t('fields.nomtranLiqKg'),
    field: 'trsf_bs_load_kg',
    //field: 'trsb_kg',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    editable: ((pageState==='disposal' && !!arm)? true : false),
  },
];

export default columns;
