const columns = (t, listing) => [
  {
    headerName: t('fields.wriNumber'),
    field: 'wri_number',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.wriIdStatus'),
    field: 'id_status_desc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    width: 130,
    suppressSizeToFit: true,
    hide: !listing,
  },
  {
    headerName: t('fields.wriProducerName'),
    field: 'producer_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 300,
    suppressSizeToFit: true,
    hide: !listing,
  },
  {
    headerName: t('fields.wriPickupLocation'),
    field: 'pickup_location',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 300,
    suppressSizeToFit: true,
    hide: !listing,
  },
  {
    headerName: t('fields.wriWasteClassification'),
    field: 'waste_classification',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: !listing,
  },
  {
    headerName: t('fields.wriVehicleRegistration'),
    field: 'vehicle_registration',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.wriContractNumber'),
    field: 'contract_number',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: !listing,
  },
  {
    headerName: t('fields.wriEffectiveDate'),
    field: 'wri_effective_date',
    cellRenderer: 'DateRenderer',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.wriExpiryDate'),
    field: 'wri_expiry_date',
    cellRenderer: 'DateRenderer',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.wriStatus'),
    field: 'wri_status_desc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    width: 130,
    suppressSizeToFit: true,
    hide: false,
  },
];

export default columns;
