const columns = (t, config) => [
  {
    headerName: t('fields.companyCode'),
    field: 'cmpy_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.companyName'),
    field: 'cmpy_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 300,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.companyLogo'),
    field: 'cmpy_logo',
    sortable: true,
    resizable: true,
    cellRenderer: 'ImageRenderer',
    cellRendererParams: {
      assets_folder: 'companys',
    },
    width: 80,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.plantCode'),
    field: 'cmpy_plant',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t(config?.siteLabelUser + 'fields.aoiNumber'),
    field: 'cmpy_aoi',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.siteManager'),
    field: 'site_manager',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.schdSupplier'),
    field: 'supplier',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.schdCarrier'),
    field: 'carrier',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 90,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.customer'),
    field: 'customer',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.drawer'),
    field: 'drawer',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.issuer'),
    field: 'issuer',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 90,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.employer'),
    field: 'employer',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 110,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.host'),
    field: 'host',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    width: 80,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.cmpyPidxCarrier'),
    field: 'cmpy_pidx_carrier',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: !config?.siteEnabledPIDX,
    width: 250,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.cmpyPidxSupplier'),
    field: 'cmpy_pidx_supplier',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: !config?.siteEnabledPIDX,
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.cmpyPidxDrawer'),
    field: 'cmpy_pidx_drawer',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: !config?.siteEnabledPIDX,
    width: 160,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.cmpyPidxCustomer'),
    field: 'cmpy_pidx_customer',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: !config?.siteEnabledPIDX,
    width: 180,
    suppressSizeToFit: true,
  },
];

export default columns;
