const columns = (config, t) => [
  {
    headerName: `${t('fields.bayArm')}`,
    field: 'stream_armcode',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 180,
    pinned: 'left',
  },
  {
    headerName: `${t('fields.bayMeter')}`,
    field: 'stream_mtrcode',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: `${t('fields.bayInjector')}`,
    field: 'stream_injcode',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: t('fields.bayTankCode'),
    field: 'tank_code',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.bayTankName'),
    field: 'tank_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.terminalCode'),
    field: 'tank_terminal',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: true,
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.terminal'),
    field: 'tank_sitename',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.baseProductCode'),
    field: 'tank_base',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 200,
  },
  {
    headerName: t('fields.baseProductName'),
    field: 'tank_base_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 200,
  },
  {
    headerName: t('fields.productCategory'),
    field: 'tank_bclass_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 200,
  },
  {
    headerName: `${t('fields.standardDensity')} (${t('units.kg/m3')})`,
    field: 'tank_density',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 240,
  },
];

export default columns;
