import _ from 'lodash';

const columns = (t, reasons) => [
  {
    headerName: t('fields.baseOwnerTransNo'),
    field: 'ownship_trsa_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    hide: false,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerNo'),
    field: 'ownship_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    hide: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransSuppCode'),
    field: 'supp_cmpy',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransSuppName'),
    field: 'cmpy_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 280,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransProdCode'),
    field: 'base_prod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 140,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransProduct'),
    field: 'base_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransProdClassDesc'),
    field: 'bclass_desc',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 240,
    suppressSizeToFit: true,
    hide: true,
  },

  {
    headerName: t('fields.baseOwnerQuantity'), //+ ' (' + t('units.ltr') + ')',
    field: 'ownship_qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerTransQuantity'), //+ ' (' + t('units.ltr') + ')',
    field: 'qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransUnitCode'),
    field: 'ownship_unit',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransUnit'),
    field: 'description',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransReason'),
    field: 'reason',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 150,
    suppressSizeToFit: true,
    cellRenderer: 'ListRenderer',
    cellRendererParams: {
      values: _.uniq(
        _.map(reasons, (item) => {
          return { code: item.reason_id, name: item.reason_text };
        })
      ),
    },
  },
  {
    headerName: t('fields.baseOwnerTransReason'),
    field: 'reason_text',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 200,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransTime'),
    field: 'trsa_time',
    sortable: true,
    resizable: true,
    width: 150,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
];

export default columns;
