const columns = t => [
  {
    headerName: t('fields.code'),
    field: 'tnkr_code',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.name'),
    field: 'tnkr_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.carrier'),
    field: 'tnkr_carrier_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
  },
  {
    headerName: t('fields.owner'),
    field: 'tnkr_owner_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
  },
  {
    headerName: t('fields.equipmentType'),
    field: 'tnkr_eqpt_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
  },
  {
    headerName: t('fields.baseDepot'),
    field: 'tnkr_base_site_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
  },
  {
    headerName: t('fields.locked'),
    field: 'tnkr_lock',
    sortable: true,
    resizable: true,
    cellRenderer: 'LockRenderer',
    filter: 'BooleanFilter',
  },
  {
    headerName: t('fields.active'),
    field: 'tnkr_active',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    filter: 'BooleanFilter',
  },
  {
    headerName: t('fields.bayCheck'),
    field: 'tnkr_bay_loop_ch',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    filter: 'BooleanFilter',
  },
  {
    headerName: t('fields.archived'),
    field: 'tnkr_archive',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    filter: 'BooleanFilter',
  },
  {
    headerName: t('fields.lastModified'),
    field: 'tnkr_last_modified',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.lastUsed'),
    field: 'tnkr_last_used',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
  },
];

export default columns;
