const columns = (t, config) => [
  {
    headerName: t('fields.atgFieldCode'),
    field: 'atg_field_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 140,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.atgFieldName'),
    field: 'atg_field_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.atgFieldLabel'),
    field: 'atg_field_label',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.atgFieldType'),
    field: 'atg_field_type',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: false,
  },

  {
    headerName: t('fields.atgFieldActive'),
    field: 'atg_field_active',
    sortable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    resizable: true,
    suppressSizeToFit: true,
    width: 160,
    hide: false,
  },

  {
    headerName: t('fields.atgFieldCreated'),
    field: 'atg_field_created',
    cellRenderer: 'DateRenderer',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.atgFieldUpdated'),
    field: 'atg_field_updated',
    cellRenderer: 'DateRenderer',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.atgFieldUser'),
    field: 'atg_field_user',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.atgFieldUserName'),
    field: 'atg_field_username',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.atgFieldUserDesc'),
    field: 'atg_field_userdesc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
    hide: true,
  },
];

export default columns;
