const columns = t => [
  {
    headerName: t('fields.drawerCode'),
    field: 'prod_cmpycode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true, 
    pinned: "left",
  },
  {
    headerName: t('fields.oitemDrwrName'),
    field: 'prod_cmpyname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 180,
    pinned: "left",
  },
  {
    headerName: t('fields.productCode'),
    field: 'prod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
    pinned: "left",
  },
  {
    headerName: t('fields.productName'),
    field: 'prod_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 220,
    pinned: "left",
  },
  {
    headerName: t('fields.prodCompliant'),
    field: 'prod_is_compliant',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    cellRenderer: 'BooleanRenderer',
    width: 120,
  },
  {
    headerName: t('fields.locked'),
    field: 'prod_is_locked',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    cellRenderer: 'BooleanRenderer',
    width: 90,
  },
  {
    headerName: t('fields.productGroupCode'),
    field: 'prod_group',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 170,
  },
  {
    headerName: t('fields.productGroup'),
    field: 'prod_groupname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.genericName'),
    field: 'prod_classdesc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.isBlend'),
    field: 'prod_is_blend',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.loadToleranceCheck'),
    field: 'prod_ldtol_flag',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: t('fields.lowerLimit'),
    field: 'prod_ldtol_ntol',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.upperLimit'),
    field: 'prod_ldtol_ptol',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.hazchemID'),
    field: 'prod_hazid',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.technicalName'),
    field: 'prod_hazname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.hazchemClass'),
    field: 'prod_hazclass',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.hazchemCode'),
    field: 'prod_hazcode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.description'),
    field: 'prod_desc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
];

export default columns;
