const columns = (t, config) => [
  {
    headerName: t('fields.prodCmpycode'),
    field: 'prod_cmpycode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    pinned: 'left',
  },
  {
    headerName: t('fields.prodCmpyname'),
    field: 'prod_cmpyname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 180,
    pinned: 'left',
  },
  {
    headerName: t('fields.prodCode'),
    field: 'prod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
    pinned: 'left',
  },
  {
    headerName: t('fields.prodName'),
    field: 'prod_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 220,
    pinned: 'left',
  },
  {
    headerName: t('fields.prodWriRequired'),
    field: 'prod_wri_reqd',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    cellRenderer: 'BooleanRenderer',
    width: 145,
    hide: !config.wriEnable,
  },
  {
    headerName: t('fields.prodIsCompliant'),
    field: 'prod_is_compliant',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    cellRenderer: 'BooleanRenderer',
    width: 140,
  },
  {
    headerName: t('fields.locked'),
    field: 'prod_is_locked',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    cellRenderer: 'BooleanRenderer',
    width: 90,
    hide: !config.siteUseProdLock,
  },
  {
    headerName: t('fields.prodGroup'),
    field: 'prod_group',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 170,
  },
  {
    headerName: t('fields.prodGroupname'),
    field: 'prod_groupname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.prodPrice'),
    field: 'prod_price',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.prodPriceunit'),
    field: 'prod_priceunit',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.prodClass'),
    field: 'prod_class',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
    hide: true,
  },
  {
    headerName: t('fields.prodClass'),
    field: 'prod_classdesc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },

  {
    headerName: t('fields.prodTextcolor'),
    field: 'prod_textcolor',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.prodBackcolor'),
    field: 'prod_backcolor',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.prodRptunit'),
    field: 'prod_rptunit',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.prodRptunitname'),
    field: 'prod_rptunitname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.prodRpttemp'),
    field: 'prod_rpttemp',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.prodNumber'),
    field: 'prod_number',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },

  {
    headerName: t('fields.prodIsBlend'),
    field: 'prod_is_blend',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.prodLdtolFlag'),
    field: 'prod_ldtol_flag',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: t('fields.prodLdtolNtol'),
    field: 'prod_ldtol_ntol',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.prodLdtolPtol'),
    field: 'prod_ldtol_ptol',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.prodHazid'),
    field: 'prod_hazid',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.prodHazname'),
    field: 'prod_hazname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.prodHazclass'),
    field: 'prod_hazclass',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.prodHazcode'),
    field: 'prod_hazcode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
  },

  {
    headerName: t('fields.prodHazrisk'),
    field: 'prod_hazrisk',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.prodHazemrg'),
    field: 'prod_hazemrg',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.prodHazpackgrp'),
    field: 'prod_hazpackgrp',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
  {
    headerName: t('fields.prodHazpackmthd'),
    field: 'prod_hazpackmthd',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },

  {
    headerName: t('fields.prodCheckHotVolume'),
    field: 'prod_check_hot_volume',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    cellRenderer: 'BooleanRenderer',
    width: 100,
    hide: !config.manageHotProduct,
  },
  {
    headerName: t('fields.prod15Density'),
    field: 'prod_15_density',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
    hide: !config.manageHotProduct,
  },
  {
    headerName: t('fields.prodHotTemp'),
    field: 'prod_hot_temp',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: !config.manageHotProduct,
  },

  {
    headerName: t('fields.prodCheck2ndDrawer'),
    field: 'prod_check_2nd_drawer',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    cellRenderer: 'BooleanRenderer',
    width: 100,
    hide: !config.manageDCS,
  },
  {
    headerName: t('fields.prod2ndDrawerCode'),
    field: 'prod_2nd_drawer',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: !config.manageDCS,
  },
  {
    headerName: t('fields.prod2ndDrawer'),
    field: 'prod_2nd_drawer_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 150,
    hide: !config.manageDCS,
  },
  {
    headerName: t('fields.prod2ndProductCode'),
    field: 'prod_2nd_product',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
    hide: !config.manageDCS,
  },
  {
    headerName: t('fields.prod2ndProduct'),
    field: 'prod_2nd_product_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
    hide: !config.manageDCS,
  },

  {
    headerName: t('fields.prodDesc'),
    field: 'prod_desc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 130,
  },

  {
    headerName: t('fields.copsGuardMasterProdCode'),
    field: 'prod_guardmaster_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 240,
    hide: !config.siteEnabledCOPS,
  },
  {
    headerName: t('fields.copsGuardMasterProdQualityID'),
    field: 'prod_guardmaster_quality',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: !config.siteEnabledCOPS,
  },
  {
    headerName: t('fields.copsGuardMasterProdQualityCode'),
    field: 'prod_guardmaster_qltycode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
    hide: true, // !config.siteEnabledCOPS,
  },
  {
    headerName: t('fields.copsGuardMasterProdQuality'),
    field: 'prod_guardmaster_qltyname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 250,
    hide: !config.siteEnabledCOPS,
  },

  {
    headerName: t('fields.prodPidxCode'),
    field: 'prod_pidx_code',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: !config?.siteEnabledPIDX,
    width: 200,
    suppressSizeToFit: true,
  },
];

export default columns;
