const columns = (t, config) => [
  {
    headerName: t('fields.genericName'),
    field: 'gen_prod_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 160,
    // pinned: "left",
  },
  {
    headerName: t('fields.numberOfDrawerProducts'),
    field: 'gen_prod_count',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 240,
    // pinned: "left",
  },
  {
    headerName: t('fields.prodCmpycode'),
    field: 'gen_dprod_cmpycode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 180,
  },
  {
    headerName: t('fields.prodCmpyname'),
    field: 'gen_dprod_cmpyname',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 240,
  },
  {
    headerName: t('fields.drawerProdCode'),
    field: 'gen_dprod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 220,
  },
  {
    headerName: t('fields.drawerProdName'),
    field: 'gen_dprod_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true, 
    width: 300,
  },
];

export default columns;
