const columns = (t, config) => [
  {
    headerName: t('fields.genericName'),
    field: 'gen_prod_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    // suppressSizeToFit: true, 
    width: 160,
    // pinned: "left",
  },
  {
    headerName: t('fields.numberOfDrawerProducts'),
    field: 'gen_prod_count',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    // suppressSizeToFit: true, 
    width: 180,
    // pinned: "left",
  },
  {
    headerName: t('fields.oitemProdCmpy'),
    field: 'gen_dprod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    // suppressSizeToFit: true, 
    // width: 80,
  },
  {
    headerName: t('fields.oitemDrwrName'),
    field: 'gen_dprod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    // suppressSizeToFit: true, 
    // width: 80,
  },
  {
    headerName: t('fields.drawerProdCode'),
    field: 'gen_dprod_cmpycode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    // suppressSizeToFit: true, 
    // width: 80,
  },
  {
    headerName: t('fields.drawerProdName'),
    field: 'gen_dprod_code',
    filter: 'gen_dprod_cmpyname',
    sortable: true,
    resizable: true,
    // suppressSizeToFit: true, 
    // width: 80,
  },
];

export default columns;
