const columns = (t) => [
  {
    headerName: t('fields.odOrderNo'),
    field: 'od_order_no',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.odDocName'),
    field: 'od_doc_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 400,
  },
  {
    headerName: t('fields.odDocFolder'),
    field: 'od_doc_folder',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.odDocSize'),
    field: 'od_doc_size',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.odDocCreator'),
    field: 'od_doc_creator',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 150,
  },
  {
    headerName: t('fields.odDocCreator'),
    field: 'od_doc_creator_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    suppressSizeToFit: true,
    width: 150,
  },
  {
    headerName: t('fields.odDocCreated'),
    field: 'od_doc_created',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.odDocDownloaded'),
    field: 'od_doc_downloaded',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.odDocDnldcounts'),
    field: 'od_doc_dnldcounts',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    suppressSizeToFit: true,
    width: 200,
  },
];

export default columns;
