const columns = (t) => [
  {
    headerName: t('fields.asCode'),
    field: 'as_code',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.asName'),
    field: 'as_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.asIP'),
    field: 'as_ip',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.asUsername'),
    field: 'as_username',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.asPassword'),
    field: 'as_password',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.asBaseDN'),
    field: 'as_base_dn',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.asFilters'),
    field: 'as_filters',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.asReturns'),
    field: 'as_returns',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.asType'),
    field: 'as_type',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.asNote'),
    field: 'as_note',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.asRole'),
    field: 'as_role',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.asRoleName'),
    field: 'as_role_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
  },
  {
    headerName: t('fields.asActive'),
    field: 'as_active',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
  },
];

export default columns;
