const columns = (t, value) => [
  {
    headerName: t('fields.terminalCode'),
    field: 'term_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 150,
  },
  {
    headerName: t('fields.terminalName'),
    field: 'term_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.trmgrpActive'),
    field: 'tgl_link_active',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    // cellEditor: 'BooleanEditor',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.trmgrpCode'),
    field: 'trmgrp_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
    hide: !value,
  },
  {
    headerName: t('fields.trmgrpName'),
    field: 'trmgrp_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 140,
    hide: !value,
  },
  {
    headerName: t('fields.trmgrpNote'),
    field: 'trmgrp_note',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
    hide: true,
  },
  {
    headerName: t('fields.trmgrpActive'),
    field: 'trmgrp_active',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 100,
    hide: true,
  },
];

export default columns;
