const columns = (t) => [
  {
    headerName: t('fields.recordId'),
    field: 'source_exists',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.siteId'),
    field: 'report_jasper_file',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 80,
  },
  {
    headerName: t('fields.referenceNumber'),
    field: 'report_type_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.transactionDate'),
    field: 'report_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.productId'),
    field: 'report_desc',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 110,
  },
  {
    headerName: t('fields.ambientQuantity'),
    field: 'report_ondemand_flag',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 150,
  },
  {
    headerName: t('fields.standardQuantity'),
    field: 'report_closeout_flag',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.temperature'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.iButton'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.vehicle'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.userId'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.armId'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.bayId'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.tankId'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.odometer'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.fileName'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.tripNumber'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.failedCount'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.status'),
    field: 'report_closeout_flag2_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
];

export default columns;
