const columns = t => [
  {
    headerName: t('fields.reportCmpycode'),
    field: 'report_cmpycode',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.reportCmpyname'),
    field: 'report_cmpyname',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 170,
  },
  {
    headerName: t('fields.reportType'),
    field: 'report_type_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.reportName'),
    field: 'report_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 240,
  },
  {
    headerName: t('fields.reportDesc'),
    field: 'report_desc',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 140,
  },
  {
    headerName: t('fields.reportJasperFile'),
    field: 'report_jasper_file',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 200,
  },
  {
    headerName: t('fields.reportCmpyemail'),
    field: 'report_cmpyemail',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.reportEnabled'),
    field: 'report_enabled',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.reportActive'),
    field: 'report_active',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.reportCanprint'),
    field: 'report_canprint',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.reportCanemail'),
    field: 'report_canemail',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.reportOndemandFlag'),
    field: 'report_ondemand_flag',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: t('fields.reportCloseoutFlag'),
    field: 'report_closeout_flag',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 160,
  },
];

export default columns;
