const columns = (t, config) => [
  {
    headerName: t('fields.id'),
    field: 'pmv_number',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    pinned: 'left',
    width: 60,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.sourceUnit'),
    field: 'pmv_srccode',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.sourceType'),
    field: 'pmv_srctype_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    // suppressSizeToFit: true,
    width: 110,
  },

  {
    headerName: t('fields.destinationUnit'),
    field: 'pmv_dstcode',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 110,
  },
  {
    headerName: t('fields.destinationType'),
    field: 'pmv_dsttype_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 150,
  },
  {
    headerName: t('fields.product'),
    field: 'pmv_prdctlnk',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t(config?.siteLabelUser + 'fields.batch'),
    field: 'pmv_batchcode',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    // suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.state'),
    field: 'pmv_status_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.class'),
    field: 'pmv_trans_type_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.quantity'),
    field: 'pmv_intended_qty',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.initialStandardVolume'),
    field: 'pmv_opening_qty',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.density'),
    field: 'pmv_obsvd_dens',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 110,
  },
  {
    headerName: t('fields.nomtranNomId'),
    field: 'pmv_mv_id',
    sortable: true,
    resizable: true,
    hide: !config.prodmvmnt_to_movement,
    suppressSizeToFit: true,
    width: 80,
  },
  {
    headerName: t('fields.progress'),
    field: 'percentage',
    sortable: true,
    resizable: true,
    cellRenderer: 'ProgressRenderer',
    width: 250,
    pinned: 'right',
    suppressSizeToFit: true,
  },
];

export default columns;
