const columns = (t) => [
  {
    headerName: t('fields.id'),
    field: 'pmv_number',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    pinned: 'left',
    width: 100,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.source'),
    field: 'pmv_srccode',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.sourceType'),
    field: 'pmv_srctype_name',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 110,
  },

  {
    headerName: t('fields.destination'),
    field: 'pmv_dstcode',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 110,
  },
  {
    headerName: t('fields.destinationType'),
    field: 'pmv_dsttype_name',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 150,
  },
  {
    headerName: t('fields.product'),
    field: 'pmv_prdctlnk',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.batch'),
    field: 'pmv_batchcode',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.state'),
    field: 'pmv_status_name',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 150,
  },
  {
    headerName: t('fields.class'),
    field: 'pmv_trans_type_name',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.quantity'),
    field: 'pmv_intended_qty',
    sortable: true,
    resizable: true,

    width: 100,
  },
  {
    headerName: t('fields.initialStandardVolume'),
    field: 'pmv_opening_qty',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.density'),
    field: 'pmv_obsvd_dens',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.progress'),
    field: 'percentage',
    sortable: true,
    resizable: true,
    cellRenderer: 'ProgressRenderer',
    width: 250,
    pinned: 'right',
    suppressSizeToFit: true,
  },
];

export default columns;
