const columns = (t, pageState, form) => [
  {
    headerName: `${t('fields.addressAction')}`,
    field: 'ddd_action',
    width: 32,
    //checkboxSelection: true,
    cellRenderer: 'MarkRenderer',
    // suppressSizeToFit: true,
    pinned: 'left',
    hide: true,
  },
  {
    headerName: t('fields.dddDdNumber'),
    field: 'ddd_dd_number',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
    // suppressSizeToFit: true,
  },
  {
    headerName: t('fields.dddDdSuppCode'),
    field: 'ddd_dd_supp_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
    // suppressSizeToFit: true,
  },
  {
    headerName: t('fields.dddDdSuppName'),
    field: 'ddd_dd_supp_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
    // suppressSizeToFit: true,
  },
  {
    headerName: t('fields.dddDdTripOrdNo'),
    field: 'ddd_dd_tripord_no',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
    // suppressSizeToFit: true,
  },
  {
    headerName: t('fields.dddDdLdType'),
    field: 'ddd_dd_ld_type',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
    // suppressSizeToFit: true,
  },
  {
    headerName: t('fields.dddDdLoadTypeName'),
    field: 'ddd_dd_load_typename',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 120,
    // suppressSizeToFit: true,
  },
  {
    headerName: t('fields.dddTemplId'),
    field: 'ddd_templ_id',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
    // suppressSizeToFit: true,
  },
];

export default columns;
