
  CREATE OR REPLACE FORCE VIEW "GUI_ALLOCATION_PERIODS" ("AIPRD_TYPE", "AIPRD_TYPENAME", "AIPRD_CMPYCODE", "AIPRD_CMPYNAME", "AIPRD_PRODCODE", "AIPRD_PRODNAME", "AIPRD_SUPPCODE", "AIPRD_SUPPNAME", "AIPRD_INDEX", "AIPRD_DAYSTART", "AIPRD_DAYEND", "AIPRD_PRODUNIT", "AIPRD_UNITNAME", "AIPRD_QTYLIMIT", "AIPRD_QTYUSED", "AIPRD_QTYLEFT", "AIPRD_LOCK", "AIPRD_LOCKNAME") AS 
  select
	aiprd.ALCH_ALP_ALL_ATKY_AT_TYPE			as AIPRD_TYPE
	, ctype.COMPANY_NAME             		as AIPRD_TYPENAME
	, aiprd.ALCH_ALP_ALL_ATKY_AT_CMPY		as AIPRD_CMPYCODE
	, acmpy.CMPY_NAME                		as AIPRD_CMPYNAME
	, aiprd.ALCH_ALP_ALL_PROD_PRODCODE		as AIPRD_PRODCODE
	, aprod.PROD_NAME                		as AIPRD_PRODNAME
	, aiprd.ALCH_ALP_ALL_PROD_PRODCMPY		as AIPRD_SUPPCODE
	, pcmpy.CMPY_NAME                		as AIPRD_SUPPNAME
	, aiprd.ALL_CHILD_P_NO					as AIPRD_INDEX
	, aiprd.ALL_CH_STRT_DAY					as AIPRD_DAYSTART
	, aiprd.ALL_CH_END_DAY					as AIPRD_DAYEND
	, aiprd.ALL_CH_UNIT						as AIPRD_PRODUNIT
	, aunit.DESCRIPTION						as AIPRD_UNITNAME
	, aiprd.ALL_CH_QTY						as AIPRD_QTYLIMIT
	, aiprd.ALL_CH_USED						as AIPRD_QTYUSED
	, (aiprd.ALL_CH_QTY-aiprd.ALL_CH_USED)	as AIPRD_QTYLEFT
	, alloc.LOCKAL_LOCK     				as AIPRD_LOCK
	, ltype.ALLOC_LOCK_NAME					as AIPRD_LOCKNAME
from
	ALL_CHILD								aiprd
	, COMPANY_TYP 							ctype
	, COMPANYS								acmpy
	, PRODUCTS 								aprod
	, COMPANYS								pcmpy
	, UNIT_SCALE_VW							aunit
	, LOCKAL								alloc
	, ALLOC_LOCK_TYP						ltype
where
-- 	( ( (SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') = 'N') and (pcmpy.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE')) )
	( ( (SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') = 'N') 
	   and (pcmpy.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE') 
-- 	    or (aiprd.ALCH_ALP_ALL_ATKY_AT_TYPE=1 and acmpy.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE'))) )
	    or (acmpy.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE'))
		or (aiprd.ALCH_ALP_ALL_ATKY_AT_TYPE=2 and acmpy.CMPY_CODE in (select child_cmpy_code from company_relation where parent_cmpy_code=SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE') and parent_cmpy_role=1 and child_cmpy_role=2) ) 
		) ) 
	or ( SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE') IS NULL )
	or ( SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') = 'Y' )
	or ( SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') IS NULL) )
	and aiprd.ALCH_ALP_ALL_ATKY_AT_TYPE = ctype.COMPANY_ID
	and aiprd.ALCH_ALP_ALL_ATKY_AT_CMPY = acmpy.CMPY_CODE
	and aiprd.ALCH_ALP_ALL_PROD_PRODCODE = aprod.PROD_CODE
	and aiprd.ALCH_ALP_ALL_PROD_PRODCMPY = aprod.PROD_CMPY
	and aiprd.ALCH_ALP_ALL_PROD_PRODCMPY = pcmpy.CMPY_CODE
	and aiprd.ALL_CH_UNIT = aunit.UNIT_ID
	and aiprd.ALCH_ALP_ALL_ATKY_AT_TYPE = alloc.LOCKATYP_AT_TYPE
	and aiprd.ALCH_ALP_ALL_ATKY_AT_CMPY = alloc.LOCKATYP_AT_CMPY
	and aiprd.ALCH_ALP_ALL_PROD_PRODCMPY = alloc.LOCKAL_SUPL
	and alloc.LOCKAL_LOCK = ltype.ALLOC_LOCK_ID;
