
  CREATE OR REPLACE FORCE VIEW "GUI_ALLOCATION_ITEMS" ("AITEM_TYPE", "AITEM_TYPENAME", "AITEM_CMPYCODE", "AITEM_CMPYNAME", "AITEM_PRODCODE", "AITEM_PRODNAME", "AITEM_SUPPCODE", "AITEM_SUPPNAME", "AITEM_QTYLIMIT", "AITEM_QTYUSED", "AITEM_QTYLEFT", "AITEM_PRODUNIT", "AITEM_UNITNAME", "AITEM_PERCHILD") AS 
  select
	aitem.ALL_ATKY_AT_TYPE			as AITEM_TYPE
	, ctype.COMPANY_NAME			as AITEM_TYPENAME
	, aitem.ALL_ATKY_AT_CMPY		as AITEM_CMPYCODE
	, acmpy.CMPY_NAME				as AITEM_CMPYNAME
	, aitem.ALL_PROD_PRODCODE		as AITEM_PRODCODE
	, aprod.PROD_NAME				as AITEM_PRODNAME
	, aitem.ALL_PROD_PRODCMPY		as AITEM_SUPPCODE
	, pcmpy.CMPY_NAME				as AITEM_SUPPNAME
	, aitem.ALLOC_LIMIT				as AITEM_QTYLIMIT
	, (aitem.ALLOC_LIMIT-aitem.ALLOC_LEFT)				as AITEM_QTYUSED
	, aitem.ALLOC_LEFT				as AITEM_QTYLEFT
	, aitem.ALLOC_UNITS				as AITEM_PRODUNIT
	, aunit.DESCRIPTION				as AITEM_UNITNAME
	, aitem.ALLOC_PER_CHILD			as AITEM_PERCHILD
from
	ALLOCS							aitem
	, COMPANY_TYP 					ctype
	, COMPANYS						acmpy
	, PRODUCTS 						aprod
	, COMPANYS						pcmpy
	, UNIT_SCALE_VW					aunit
where
-- 	( ( (SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') = 'N') and (pcmpy.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE')) )
	( ( (SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') = 'N') 
	   and (pcmpy.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE') 
-- 	    or (aitem.ALL_ATKY_AT_TYPE=1 and acmpy.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE'))) )
	    or (acmpy.CMPY_CODE = SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE'))
		or (aitem.ALL_ATKY_AT_TYPE=2 and acmpy.CMPY_CODE in (select child_cmpy_code from company_relation where parent_cmpy_code=SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE') and parent_cmpy_role=1 and child_cmpy_role=2) ) 
		) ) 
	or ( SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE') IS NULL )
	or ( SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') = 'Y' )
	or ( SYS_CONTEXT('CONN_CONTEXT', 'ISMANAGER') IS NULL) )
	and aitem.ALL_ATKY_AT_TYPE = ctype.COMPANY_ID
	and aitem.ALL_ATKY_AT_CMPY = acmpy.CMPY_CODE
	and aitem.ALL_PROD_PRODCODE = aprod.PROD_CODE
	and aitem.ALL_PROD_PRODCMPY = aprod.PROD_CMPY
	and aitem.ALL_PROD_PRODCMPY = pcmpy.CMPY_CODE
	and aitem.ALLOC_UNITS = aunit.UNIT_ID;
