const columns = (t) => [
  {
    headerName: t('fields.schdOrderId'),
    field: 'schd_order_id',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.schdSuppCode'),
    field: 'schd_supp_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.schdSupplier'),
    field: 'schd_supplier',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
  },
  {
    headerName: t('fields.schdTripNo'),
    field: 'schd_trip_no',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.schdCmptNo'),
    field: 'schd_cmpt_no',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 80,
  },
  {
    headerName: t('fields.schdProdCode'),
    field: 'schd_prod_code',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.schdProdCmpy'),
    field: 'schd_prod_cmpy',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 150,
  },
  {
    headerName: t('fields.schdProdName'),
    field: 'schd_prod_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 150,
  },
  {
    headerName: t('fields.schdProdQty'),
    field: 'schd_prod_qty',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.schdProdUnit'),
    field: 'schd_prod_unit',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    editable: false,
    width: 100,
  },
  {
    headerName: t('fields.schdUnitName'),
    field: 'schd_unit_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    editable: false,
    width: 100,
  },
];

export default columns;
