const columns = (t) => [
  {
    headerName: t('fields.businessProcessReason'),
    field: 'mr_action',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.movementType'),
    field: 'mr_type_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.originalMovementType'),
    field: 'mr_mov_type_ori',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.originalReasonCode'),
    field: 'mr_reason_code_ori',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.reversalMovementType'),
    field: 'mr_mov_type_rev',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.reversalReasonCode'),
    field: 'mr_reason_code_rev',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.showComment'),
    field: 'mr_show_comment',
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.status'),
    field: 'mr_flag_desc',
    filter: 'FuzzyFilter',
    // cellRenderer: 'BooleanRenderer',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.countReasonSpecmove'),
    field: 'mlitm_count',
    filterable: true,
    sortable: true,
    resizable: true,
    width: 140,
    // hide: true,
  },
];

export default columns;
