const columns = (t, config) => [
  {
    headerName: t('fields.terminalCode'),
    field: 'tank_site',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: true,
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.terminal'),
    field: 'tank_sitename',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: !config?.siteUseMultiTerminals,
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: t('fields.code'),
    field: 'tank_code',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    width: 90,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.location'),
    field: 'tank_location',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseProductName'),
    field: 'base_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 180,
  },

  {
    headerName: t('fields.waterLevel') + ' (' + t('units.mm') + ')',
    field: 'tank_water_lvl',
    sortable: true,
    resizable: true,
    hide: !config?.useWaterStrapping,
    suppressSizeToFit: true,
    width: 170,
  },
  {
    headerName: t(config?.siteLabelUser + 'fields.waterVolume') + ' (' + t('units.ltr') + ')',
    field: 'tank_water',
    sortable: true,
    resizable: true,
    hide: true,
    suppressSizeToFit: true,
    width: 181,
  },
  {
    headerName: `${t('fields.tankLevel')} (${t('units.mm')})`,
    field: 'tank_prod_lvl',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.tankIFC') + ' (' + t('units.ltr') + ')',
    field: 'tank_ifc',
    sortable: true,
    resizable: true,
    hide: !config?.useWaterStrapping,
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: `${t('fields.temperature')} (°C)`,
    field: 'tank_temp',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 170,
  },
  {
    headerName: `${t(config?.siteLabelUser + 'fields.standardVolume')} (${t(
      config?.siteLabelUser + 'units.lcor'
    )})`,
    field: 'netvol',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 300,
  },
  {
    headerName: `${t(config?.siteLabelUser + 'fields.observedVolume')} (${t(
      config?.siteLabelUser + 'units.lobs'
    )})`,
    field: 'grossvol',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 300,
  },
  {
    headerName: `${t('fields.pumpableVolume')} (${t(config?.siteLabelUser + 'units.lobs')})`,
    field: 'pumpablevol',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 220,
  },
  {
    headerName: `${t('fields.openingStock')} (${t(config?.siteLabelUser + 'units.lcor')})`,
    field: 'usablevol',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 200,
  },
  {
    headerName: `${t('fields.bookBalance')} (${t(config?.siteLabelUser + 'units.lcor')})`,
    field: 'bookbalance',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 185,
  },
];

export default columns;
