
/*
	add contents for SCHEDULE_STATUS_TYPE
*/

insert into msg_lookup values(3054, 'CHN', '新提单');
insert into msg_lookup values(3054, 'ENG', 'NEW SCHEDULE');
insert into msg_lookup values(3055, 'CHN', '已调度');
insert into msg_lookup values(3055, 'ENG', 'SPECED');

/*
1	F	NEW SCHEDULE
3	S	SPECED
5	A	ACTIVE
7	L	LOADING
9	E	ENDED
11	D	DELIVERED OK

186	CHN	已结束
186	ENG	ENDED
334	CHN	发油中
334	ENG	LOADING
873	CHN	运送成功
873	ENG	DELIVERED OK
1056	CHN	活动的
1056	ENG	ACTIVE
*/
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SCHEDULE_STATUS_TYPE', 1, 'F', 3054);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SCHEDULE_STATUS_TYPE', 2, 'S', 3055);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SCHEDULE_STATUS_TYPE', 3, 'A', 1056);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SCHEDULE_STATUS_TYPE', 4, 'L', 334);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SCHEDULE_STATUS_TYPE', 5, 'E', 186);
insert into ENUMITEM (ENUMTYPENAME,ENUM_NO,ENUM_CODE,ENUM_TMM)values('SCHEDULE_STATUS_TYPE', 6, 'D', 873);

commit;


-- Change VIEW for SCHEDULE_STATUS_SHORT_LOOKUP

CREATE OR REPLACE VIEW SCHEDULE_STATUS_SHORT_LOOKUP
(STATUS_ID, STATUS_CODE, STATUS_TEXT)
AS 
SELECT 
	ENUMITEM.ENUM_NO STATUS_ID
	, ENUMITEM.ENUM_CODE STATUS_CODE
	, MSG_GLBL.MESSAGE STATUS_TEXT
FROM ENUMITEM,MSG_GLBL
WHERE ENUMITEM.ENUM_TMM=MSG_GLBL.MSG_ID
AND ENUMTYPENAME='SCHEDULE_STATUS_TYPE';


/

commit;
