
-- add ENUM_CODE

update ENUMITEM set ENUM_CODE='A' where ENUMTYPENAME='LOAD_ARM_TYPES' and ENUM_NO=0;
update ENUMITEM set ENUM_CODE='B' where ENUMTYPENAME='LOAD_ARM_TYPES' and ENUM_NO=1;
update ENUMITEM set ENUM_CODE='T' where ENUMTYPENAME='LOAD_ARM_TYPES' and ENUM_NO=2;


commit;


-- Change VIEW for EQUIP_LIST_LD_TYPE_LOOKUP



CREATE OR REPLACE VIEW EQUIP_LIST_LD_TYPE_LOOKUP
(LD_TYPE_ID, LD_TYPE_CODE, LD_TYPE_TEXT)
AS 
SELECT 
	ENUMITEM.ENUM_NO LD_TYPE_ID
	, ENUMITEM.ENUM_CODE LD_TYPE_CODE
	, MSG_GLBL.MESSAGE LD_TYPE_TEXT
FROM ENUMITEM,MSG_GLBL
WHERE ENUMITEM.ENUM_TMM=MSG_GLBL.MSG_ID
AND ENUMTYPENAME='LOAD_ARM_TYPES';

/

commit;
