
  CREATE OR REPLACE FORCE VIEW "RPTOBJ_PROD_DETAILS_VW" ("PROD_CODE", "PROD_CMPY", "PROD_NAME", "PROD_PROD_GROUP", "PROD_PRICE", "PROD_PRICE_UNIT", "PROD_CLASS", "PROD_TXT_COLOUR", "PROD_BACK_COLOUR", "PROD_RPT_UNIT", "PROD_RPT_TEMP", "PROD_NUMBER", "PROD_IS_BLEND", "PROD_LDTOL_FLAG", "PROD_LDTOL_PTOL", "PROD_LDTOL_NTOL", "BASE_CODE", "BASE_NAME", "BASE_PROD_GROUP", "BASE_CAT", "BASE_RPT_TUNT", "BASE_RPT_TEMP", "BASE_PUB_TEMP", "BASE_PUB_DENS", "BASE_PUB_DENS_STD", "BASE_PUB_VCF", "BASE_REAL_TEMP", "BASE_REAL_DENS", "BASE_REAL_DENS_STD", "BASE_REAL_VCF", "BASE_COMPENSATE_MODE", "BASE_COMPENSATE_PRIORITY", "LAST_UPD_TIME", "RATIO_BASE", "RAT_PROD_PRODCODE", "RAT_PROD_PRODCMPY", "RATIO_VALUE", "RAT_BLTOL_FLAG", "RAT_BLTOL_PTOL", "RAT_BLTOL_NTOL", "ADTV_FLAG", "RAT_SUB_SEQ", "RAT_SEQ", "RAT_SUB_COUNT", "RAT_COUNT", "RAT_TOTAL", "RAT_RATIO", "BASE_CLASS_NO", "BASE_CLASS_DESC", "APROD_CODE", "APROD_CMPY", "ADTV_CODE", "ADTV_NAME", "ADTV_BLTOL_FLAG", "ADTV_BLTOL_PTOL", "ADTV_BLTOL_NTOL", "ADTV_RAT_VALUE", "ADTV_SUB_SEQ", "ADTV_SEQ", "ADTV_SUB_COUNT", "ADTV_COUNT", "ADTV_RAT_TOTAL", "ADTV_RATIO") AS 
  select "PROD_CODE","PROD_CMPY","PROD_NAME","PROD_PROD_GROUP","PROD_PRICE","PROD_PRICE_UNIT","PROD_CLASS","PROD_TXT_COLOUR","PROD_BACK_COLOUR","PROD_RPT_UNIT","PROD_RPT_TEMP","PROD_NUMBER","PROD_IS_BLEND","PROD_LDTOL_FLAG","PROD_LDTOL_PTOL","PROD_LDTOL_NTOL","BASE_CODE","BASE_NAME","BASE_PROD_GROUP","BASE_CAT","BASE_RPT_TUNT","BASE_RPT_TEMP","BASE_PUB_TEMP","BASE_PUB_DENS","BASE_PUB_DENS_STD","BASE_PUB_VCF","BASE_REAL_TEMP","BASE_REAL_DENS","BASE_REAL_DENS_STD","BASE_REAL_VCF","BASE_COMPENSATE_MODE","BASE_COMPENSATE_PRIORITY","LAST_UPD_TIME","RATIO_BASE","RAT_PROD_PRODCODE","RAT_PROD_PRODCMPY","RATIO_VALUE","RAT_BLTOL_FLAG","RAT_BLTOL_PTOL","RAT_BLTOL_NTOL","ADTV_FLAG","RAT_SUB_SEQ","RAT_SEQ","RAT_SUB_COUNT","RAT_COUNT","RAT_TOTAL","RAT_RATIO","BASE_CLASS_NO","BASE_CLASS_DESC","APROD_CODE","APROD_CMPY","ADTV_CODE","ADTV_NAME","ADTV_BLTOL_FLAG","ADTV_BLTOL_PTOL","ADTV_BLTOL_NTOL","ADTV_RAT_VALUE","ADTV_SUB_SEQ","ADTV_SEQ","ADTV_SUB_COUNT","ADTV_COUNT","ADTV_RAT_TOTAL","ADTV_RATIO"
from
(
select
PRODUCTS.*
,BASE_PRODS.*
,BPR.*
,(BPR.RATIO_VALUE/BPR.RAT_TOTAL) as RAT_RATIO
,bpcls.BCLASS_NO as BASE_CLASS_NO
,bpcls.BCLASS_DESC as BASE_CLASS_DESC
from
PRODUCTS
,(
--select r0.*, b0.ADTV_FLAG
-- ,row_number() OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY, b0.ADTV_FLAG order by r0.RATIO_VALUE desc ) as RAT_SUB_SEQ
-- ,row_number() OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY order by r0.RATIO_VALUE desc ) as RAT_SEQ
-- ,count(r0.RATIO_BASE) OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY, b0.ADTV_FLAG ) as RAT_SUB_COUNT
-- ,count(r0.RATIO_BASE) OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY) as RAT_COUNT
-- ,sum(r0.RATIO_VALUE) OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY) as RAT_TOTAL
--from RATIOS r0, (select BASE_CODE, decode(BASE_CAT, 6, 1, 0) as ADTV_FLAG from BASE_PRODS) b0
--where r0.RATIO_BASE = b0.BASE_CODE
RPTOBJ_PROD_RATIOS_VW
) BPR
,BASE_PRODS
, (
				select 
					bcls.BCLASS_NO
					, NVL(bctyp.BCLASS_NAME, bcls.BCLASS_DESC)			as BCLASS_DESC
					, bcls.BCLASS_DENS_LO
					, bcls.BCLASS_DENS_HI
					, bcls.BCLASS_VCF_ALG
					, bcls.BCLASS_TEMP_LO
					, bcls.BCLASS_TEMP_HI			
				from 
					BASECLASS 			bcls
					, BCLASS_TYP		bctyp
				where 
					1=1	
					and bcls.BCLASS_NO = bctyp.BCLASS_ID(+)
) 								bpcls
where
PRODUCTS.PROD_CODE = BPR.RAT_PROD_PRODCODE
and PRODUCTS.PROD_CMPY = BPR.RAT_PROD_PRODCMPY
and BPR.RATIO_BASE = BASE_PRODS.BASE_CODE
and BASE_PRODS.BASE_CAT = bpcls.BCLASS_NO
) bpA
,(
select
PRODUCTS.PROD_CODE as APROD_CODE
,PRODUCTS.PROD_CMPY as APROD_CMPY
,BASE_PRODS.BASE_CODE as ADTV_CODE
,BASE_PRODS.BASE_NAME as ADTV_NAME
,BPR.RAT_BLTOL_FLAG as ADTV_BLTOL_FLAG
,BPR.RAT_BLTOL_PTOL as ADTV_BLTOL_PTOL
,BPR.RAT_BLTOL_NTOL as ADTV_BLTOL_NTOL
,BPR.RATIO_VALUE as ADTV_RAT_VALUE
,BPR.RAT_SUB_SEQ as ADTV_SUB_SEQ
,BPR.RAT_SEQ as ADTV_SEQ
,BPR.RAT_SUB_COUNT as ADTV_SUB_COUNT
,BPR.RAT_COUNT as ADTV_COUNT
,BPR.RAT_TOTAL as ADTV_RAT_TOTAL
,(BPR.RATIO_VALUE/BPR.RAT_TOTAL) as ADTV_RATIO
from
PRODUCTS
,(
--select r0.*, b0.ADTV_FLAG
-- ,row_number() OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY, b0.ADTV_FLAG order by r0.RATIO_VALUE desc ) as RAT_SUB_SEQ
-- ,row_number() OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY order by r0.RATIO_VALUE desc ) as RAT_SEQ
-- ,count(r0.RATIO_BASE) OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY, b0.ADTV_FLAG ) as RAT_SUB_COUNT
-- ,count(r0.RATIO_BASE) OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY) as RAT_COUNT
-- ,sum(r0.RATIO_VALUE) OVER (partition by r0.RAT_PROD_PRODCODE, r0.RAT_PROD_PRODCMPY) as RAT_TOTAL
--from RATIOS r0, (select BASE_CODE, decode(BASE_CAT, 6, 1, 0) as ADTV_FLAG from BASE_PRODS) b0
--where r0.RATIO_BASE = b0.BASE_CODE
RPTOBJ_PROD_RATIOS_VW
) BPR
,BASE_PRODS
where
PRODUCTS.PROD_CODE = BPR.RAT_PROD_PRODCODE
and PRODUCTS.PROD_CMPY = BPR.RAT_PROD_PRODCMPY
and BPR.RATIO_BASE = BASE_PRODS.BASE_CODE
and BASE_PRODS.BASE_CAT = '6'
) bpB
where
bpA.PROD_CODE = bpB.APROD_CODE(+)
and bpA.PROD_CMPY = bpB.APROD_CMPY(+)
and (bpA.RAT_SEQ = bpB.ADTV_SUB_SEQ(+));
