
  CREATE OR REPLACE FORCE VIEW "GUI_EQUIPMENT_LIST" ("EQPT_ID", "EQPT_CODE", "EQPT_TITLE", "EQPT_TANKER", "EQPT_OWNER", "EQPT_OWNER_NAME", "EQPT_ETP", "EQPT_ETP_TITLE", "EQPT_EXP_D1_DMY", "EQPT_EXP_D2_DMY", "EQPT_EXP_D3_DMY", "EQPT_LOCK", "EQPT_EMPTY_KG", "EQP_MUST_TARE_IN", "EQPT_MAX_GROSS", "EQPT_COMMENTS", "EQPT_AREA", "EQPT_AREA_NAME", "EQPT_LOAD_TYPE", "EQPT_LOAD_TYPE_NAME", "ETYP_CATEGORY") AS 
  SELECT te.EQPT_ID as EQPT_ID,
        te.EQPT_CODE as EQPT_CODE,
        te.EQPT_TITLE as EQPT_TITLE,
        tk.TC_TANKER as EQPT_TANKER,
        te.EQPT_OWNER as EQPT_OWNER,
        cp.CMPY_NAME as EQPT_OWNER_NAME,
        te.EQPT_ETP as EQPT_ETP,
        et.ETYP_TITLE as EQPT_ETP_TITLE,
        te.EQPT_EXP_D1_DMY as EQPT_EXP_D1_DMY,
        te.EQPT_EXP_D2_DMY as EQPT_EXP_D2_DMY,
        te.EQPT_EXP_D3_DMY as EQPT_EXP_D3_DMY,
        te.EQPT_LOCK as EQPT_LOCK,
        te.EQPT_EMPTY_KG as EQPT_EMPTY_KG,
        te.EQP_MUST_TARE_IN as EQP_MUST_TARE_IN,
        te.EQPT_MAX_GROSS as EQPT_MAX_GROSS,
        te.EQPT_COMMENTS as EQPT_COMMENTS,
        te.EQPT_AREA as EQPT_AREA,
        ar.AREA_NAME as EQPT_AREA_NAME,
        te.EQPT_LOAD_TYPE as EQPT_LOAD_TYPE,
        el.LD_TYPE_TEXT as EQPT_LOAD_TYPE_NAME,
        et.ETYP_CATEGORY as ETYP_CATEGORY
   FROM TRANSP_EQUIP te
      , COMPANYS cp
      , EQUIP_TYPES et
      ,(
          SELECT
              TC_TANKER, TNKR_ACTIVE, TC_EQPT
          FROM
              TANKERS
              , TNKR_EQUIP
          WHERE
              TANKERS.TNKR_CODE = TNKR_EQUIP.TC_TANKER
              AND TANKERS.TNKR_ACTIVE = 'Y'
      ) tk
      , AREA_RC ar
      , EQUIP_LIST_LD_TYPE_LOOKUP el
WHERE 
	( 
-- 		(SYS_CONTEXT ('CONN_CONTEXT', 'ISMANAGER') = 'N' AND EQPT_OWNER = SYS_CONTEXT ('CONN_CONTEXT', 'CMPYCODE'))
		( SYS_CONTEXT ('CONN_CONTEXT', 'ISMANAGER') = 'N' 
			AND ( te.EQPT_OWNER = SYS_CONTEXT ('CONN_CONTEXT', 'CMPYCODE') 
				or ( te.EQPT_OWNER in (select child_cmpy_code from company_relation where parent_cmpy_code=SYS_CONTEXT('CONN_CONTEXT', 'CMPYCODE') and parent_cmpy_role=1 and child_cmpy_role=2) ) 
			)
		)
		OR SYS_CONTEXT ('CONN_CONTEXT', 'CMPYCODE') IS NULL
		OR SYS_CONTEXT ('CONN_CONTEXT', 'ISMANAGER') = 'Y'
		OR SYS_CONTEXT ('CONN_CONTEXT', 'ISMANAGER') IS NULL
	)
	AND te.EQPT_OWNER = cp.CMPY_CODE
	AND te.EQPT_ETP = et.ETYP_ID
	AND te.EQPT_AREA = ar.AREA_K(+)
	AND te.EQPT_LOAD_TYPE = el.LD_TYPE_CODE(+)
	AND te.EQPT_ID = tk.TC_EQPT(+);
