const columns = (t) => [
  {
    headerName: t('fields.dateTime'),
    field: 'audit_datetime',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 100,
  },
  {
    headerName: t('fields.recordKey'),
    field: 'audit_record_key',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 80,
  },
  {
    headerName: t('fields.action'),
    field: 'audit_action_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.category'),
    field: 'audit_category_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.description'),
    field: 'audit_description',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 110,
  },
  {
    headerName: t('fields.valueBefore'),
    field: 'audit_value_before',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 150,
  },
  {
    headerName: t('fields.valueAfter'),
    field: 'audit_value_after',
    sortable: true,
    resizable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'BooleanRenderer',
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t('fields.userId'),
    field: 'audit_user_code',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 130,
  },
  {
    headerName: t('fields.user'),
    field: 'audit_user_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.companyCode'),
    field: 'audit_cmpy_code',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.company'),
    field: 'audit_cmpy_name',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.locationId'),
    field: 'audit_ip',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },
  {
    headerName: t('fields.column'),
    field: 'audit_column',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 90,
  },

  {
    headerName: t('fields.table'),
    field: 'audit_table',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.primaryKey'),
    field: 'audit_pkeys',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    suppressSizeToFit: true,
    width: 120,
  },
];

export default columns;
