const columns = t => [
  {
    headerName: t('fields.assignmentNo'),
    field: 'kya_key_no',
    sortable: true,
    filter: 'FuzzyFilter',
    resizable: true,
  },
  {
    headerName: t('fields.issuer'),
    field: 'kya_issuer_name',
    sortable: true,
    filter: 'MultiFilter',
    resizable: true,
  },
  {
    headerName: t('fields.assignmentType'),
    field: 'kya_type_name',
    sortable: true,
    filter: 'MultiFilter',
    resizable: true,
  },
  {
    headerName: t('fields.physicalType'),
    field: 'kya_phys_name',
    sortable: true,
    filter: 'MultiFilter',
    resizable: true,
  },
  {
    headerName: t('fields.timeCode'),
    field: 'kya_timecode',
    sortable: true,
    filter: 'MultiFilter',
    resizable: true,
  },
  {
    headerName: t('fields.locked'),
    field: 'kya_lock',
    sortable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'LockRenderer',
    resizable: true,
  },
  {
    headerName: t('fields.adhoc'),
    field: 'kya_adhoc',
    sortable: true,
    filter: 'BooleanFilter',
    cellRenderer: 'LockRenderer',
    resizable: true,
  },
  {
    headerName: t('fields.physicalTagText'),
    field: 'kya_txt',
    sortable: true,
    filter: 'FuzzySearch',
    resizable: true,
  },
  {
    headerName: t('fields.personnel'),
    field: 'kya_psnl_name',
    sortable: true,
    filter: 'MultiFilter',
    resizable: true,
  },
  {
    headerName: t('fields.role'),
    field: 'kya_role_name',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
  },
  {
    headerName: t('fields.drawer'),
    field: 'kya_draw_name',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
  },
  {
    headerName: t('fields.supplier'),
    field: 'kya_issuer_name',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
  },
  {
    headerName: t('fields.tankerCode'),
    field: 'kya_tanker',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
  },
  {
    headerName: t('fields.tankerCode'),
    field: 'kya_tanker',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
  },
  {
    headerName: t('fields.tanker'),
    field: 'kya_tnkr_name',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
  },
  {
    headerName: t('fields.equipment'),
    field: 'kya_eqpt_name',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
  },
];

export default columns;
