import _ from 'lodash';

const columns = (t, reasons, ownershipDensityVisible, config) => [
  {
    headerName: t('fields.terminal'),
    field: 'ownship_terminal',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.terminal'),
    field: 'ownship_sitedesc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    hide: !config?.siteUseMultiTerminals,
  },
  {
    headerName: t('fields.baseOwnerTransId'),
    field: 'ownship_trsa_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    hide: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransKey'),
    field: 'trsa_key',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    hide: false,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransNumber'),
    field: 'trsa_number',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    hide: false,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransQuantity'), //+ ' (' + t('units.ltr') + ')',
    field: 'qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransUnitCode'),
    field: 'trsa_unit',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 100,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransUnit'),
    field: 'description',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 150,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransReason'),
    field: 'reason',
    sortable: true,
    resizable: true,
    hide: true,
    filter: 'MultiFilter',
    width: 180,
    suppressSizeToFit: true,
    cellRenderer: 'ListRenderer',
    cellRendererParams: {
      values: _.uniq(
        _.map(reasons, (item) => {
          return { code: item.reason_id, name: item.reason_text };
        })
      ),
    },
  },
  {
    headerName: t('fields.baseOwnerTransReason'),
    field: 'reason_text',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 190,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerTransDensity') + ' (' + t('units.kg/m3') + ')',
    field: 'trsa_density',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 240,
    suppressSizeToFit: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },
  {
    headerName: t('fields.baseOwnerTransApproved'),
    field: 'trsa_approved',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.baseOwnerTransReversed'),
    field: 'trsa_reversed',
    filter: 'BooleanFilter',
    sortable: true,
    resizable: true,
    suppressSizeToFit: true,
    width: 120,
    cellRenderer: 'BooleanRenderer',
  },
  {
    headerName: t('fields.baseOwnerTransTimeCreated'),
    field: 'trsa_time',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.baseOwnerTransTimeUpdated'),
    field: 'trsa_time_updated',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.baseOwnerTransTimeApproved'),
    field: 'trsa_time_approved',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.baseOwnerTransTimeReversed'),
    field: 'trsa_time_reversed',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    cellRenderer: 'DateRenderer',
  },
  {
    headerName: t('fields.baseOwnerNo'),
    field: 'ownship_no',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    hide: true,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransProdCode'),
    field: 'base_prod_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerTransProdName'),
    field: 'base_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 240,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerTransProdClassDesc'),
    field: 'bclass_desc',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 240,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerTransComments'),
    field: 'trsa_comments',
    sortable: true,
    resizable: true,
    filter: 'MultiFilter',
    width: 200,
    suppressSizeToFit: true,
    hide: false,
  },

  {
    headerName: t('fields.baseOwnerTransTermCodeFrom'),
    field: 'trsa_terminal',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransTermDescFrom'),
    field: 'trsa_sitedesc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    hide: !config?.siteUseMultiTerminals,
  },
  {
    headerName: t('fields.baseOwnerTransSuppCodeFrom'),
    field: 'supp_cmpy',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransSuppNameFrom'),
    field: 'cmpy_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 280,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerQuantityBeforeTransFrom'), //+ ' (' + t('units.ltr') + ')',
    field: 'trsa_qty_owned',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 300,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerDensityBeforeTransFrom') + ' (' + t('units.kg/m3') + ')',
    field: 'trsa_density_owned',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: !ownershipDensityVisible,
    width: 340,
    suppressSizeToFit: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },

  {
    headerName: t('fields.baseOwnerQuantityAfterTransFrom'), //+ ' (' + t('units.ltr') + ')',
    field: 'trsa_qty_after',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 300,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerDensityAfterTransFrom') + ' (' + t('units.kg/m3') + ')',
    field: 'trsa_density_after',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 330,
    suppressSizeToFit: true,
    hide: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },

  {
    headerName: t('fields.baseOwnerQuantityCurrentFrom'), //+ ' (' + t('units.ltr') + ')',
    field: 'ownship_qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 250,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerDensityCurrentFrom') + ' (' + t('units.kg/m3') + ')',
    field: 'ownship_density',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 290,
    suppressSizeToFit: true,
    hide: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },

  {
    headerName: t('fields.baseOwnerTransTermCodeTo'),
    field: 'trsa_terminal_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerTransTermDescTo'),
    field: 'trsa_sitedesc_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    hide: !config?.siteUseMultiTerminals,
  },
  {
    headerName: t('fields.baseOwnerTransSuppCodeTo'),
    field: 'supp_cmpy_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerTransSuppNameTo'),
    field: 'cmpy_name_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 280,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.baseOwnerQuantityBeforeTransTo'), //+ ' (' + t('units.ltr') + ')',
    field: 'trsa_qty_owned_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 280,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerDensityBeforeTransTo') + ' (' + t('units.kg/m3') + ')',
    field: 'trsa_density_owned_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: !ownershipDensityVisible,
    width: 320,
    suppressSizeToFit: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },

  {
    headerName: t('fields.baseOwnerQuantityAfterTransTo'), //+ ' (' + t('units.ltr') + ')',
    field: 'trsa_qty_after_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 280,
    suppressSizeToFit: true,
    hide: false,
  },
  {
    headerName: t('fields.baseOwnerDensityAfterTransTo') + ' (' + t('units.kg/m3') + ')',
    field: 'trsa_density_after_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 320,
    suppressSizeToFit: true,
    hide: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },

  {
    headerName: t('fields.baseOwnerQuantityCurrentTo'), //+ ' (' + t('units.ltr') + ')',
    field: 'ownship_qty_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 250,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.baseOwnerDensityCurrentTo') + ' (' + t('units.kg/m3') + ')',
    field: 'ownship_density_to',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 290,
    suppressSizeToFit: true,
    hide: true,
    cellRenderer: 'DensityRenderer',
    cellRendererParams: {
      digits: String(config?.precisionDensity),
    },
  },
];

export default columns;
