const columns = (t) => [
    {
      headerName: t('fields.permissionRuleId'),
      field: 'rule_id',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      suppressSizeToFit: true, 
      width: 75,
    //   pinned: "left",
    },
    {
      headerName: t('fields.permissionRuleClass'),
      field: 'rule_casename',
      filter: 'MultiFilter',
      sortable: true,
      resizable: true,
      suppressSizeToFit: true, 
      width: 105,
    },
    {
      headerName: t('fields.equipmentType'),
      field: 'rule_etypname',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      suppressSizeToFit: true, 
      width: 140,
    },
    {
      headerName: t('fields.authorityType'),
      field: 'rule_authname',
      filter: 'FuzzyFilter',
      sortable: true,
      resizable: true,
      suppressSizeToFit: true, 
      width: 140,
    },
    {
      headerName: t('fields.firstRule'),
      field: 'rule_first',
      filter: 'BooleanFilter',
      sortable: true,
      resizable: true,
      cellRenderer: 'BooleanRenderer',
      suppressSizeToFit: true, 
      width: 105,
    },
    {
      headerName: t('fields.expiryCheck'),
      field: 'rule_expiry_check',
      filter: 'BooleanFilter',
      sortable: true,
      resizable: true,
      cellRenderer: 'BooleanRenderer',
      suppressSizeToFit: true, 
      width: 125,
    },
    {
      headerName: t('fields.operations'),
      field: 'operation',
      filter: 'MultiFilter',
      sortable: true,
      resizable: true,
      suppressSizeToFit: true, 
      width: 110,
    },
  ];
  
  export default columns;
  