const columns = (t, config) => [
  {
    headerName: t('fields.tankBatchNumber'),
    field: 'tank_batch_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 150,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.tankBatchTime'),
    field: 'tank_batch_time',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    width: 180,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.tankBatchEnd'),
    field: 'tank_batch_end',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    width: 180,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.tankCode'),
    field: 'tank_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.tankName'),
    field: 'tank_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.terminal'),
    field: 'tank_terminal',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.terminal'),
    field: 'tank_sitename',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.productCode'),
    field: 'tank_base',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.productName'),
    field: 'tank_base_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.productCategory'),
    field: 'tank_bclass_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.standardDensity') + ' (' + t('units.kg/m3') + ')',
    field: 'tank_density',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.density') + ' (' + t('units.kg/m3') + ')',
    field: 'tank_15_density',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: !(
      config?.temperatureUnit === 'degC' &&
      config?.referenceTemperature === '15' &&
      config?.vsmCompensation === '30'
    ),
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.api'),
    field: 'tank_api',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: !config?.manageAPI,
    width: 110,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.specificGravity'),
    field: 'tank_sg',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: !config?.manageAPI || !config?.siteUseSG,
    width: 110,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.standardTemperature'),
    field: 'tank_std_temp',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 160,
    suppressSizeToFit: true,
    cellRenderer: 'TemperatureRender',
  },
  {
    headerName: t('fields.sulphur'),
    field: 'tank_sulphur',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.flashPoint'),
    field: 'tank_flashpoint',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.tankViscosity'),
    field: 'tank_viscosity',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 120,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.tankRoofWeight') + ' (' + t('units.kg') + ')',
    field: 'tank_roof_weight',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 260,
    suppressSizeToFit: true,
    hide: !config?.useWaterStrapping,
  },

  {
    headerName: t('fields.adaptiveFlowControl'),
    field: 'afc_enabled',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    hide: !config.siteUseAFC,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.adaptiveArmPriority'),
    field: 'afc_priority',
    sortable: true,
    filter: 'MultiFilter',
    resizable: true,
    hide: !config.siteUseAFC,
    width: 200,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.tankDensityMode'),
    field: 'tank_dens_mode',
    sortable: true,
    filter: 'BooleanFilter',
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    hide: false,
    width: 200,
    suppressSizeToFit: true,
  },
];

export default columns;
