const columns = (t, visible, config) => [
  {
    headerName: t('fields.tkownerCode'),
    field: 'cmpy_code',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.tkownerName'),
    field: 'cmpy_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 280,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.productCode'),
    field: 'tank_base',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 140,
    suppressSizeToFit: true,
    hide: !visible,
  },
  {
    headerName: t('fields.productName'),
    field: 'tank_base_name',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 240,
    suppressSizeToFit: true,
    hide: !visible,
  },

  {
    headerName: t('fields.tkoPercentage'),
    field: 'tko_percentage',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    cellRenderer: 'QuantityRenderer',
    cellRendererParams: {
      digits: '4',
      min: '0',
    },
  },
  {
    headerName: t('fields.tkownerQty'), //+ ' (' + t('units.ltr') + ')',
    field: 'tkowner_qty',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
  },

  {
    headerName: t('fields.tkoStdLtr'), // + ' (' + t('units.ltr') + ')',
    field: 'tko_std_ltr',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.tkoAmbLtr'), // + ' (' + t('units.ltr') + ')',
    field: 'tko_amb_ltr',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    hide: true,
  },
  {
    headerName: t('fields.tkoKg') + ' (' + t('units.kg') + ')',
    field: 'tko_kg',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    width: 180,
    suppressSizeToFit: true,
    hide: true,
  },
];

export default columns;
