const columns = (t) => [
  {
    headerName: t('fields.bay'),
    field: 'trsa_bay_cd',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.transactionNumber'),
    field: 'trsa_id',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.supplier'),
    field: 'trsa_suppdesc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.tripNumber'),
    field: 'trsa_trip',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.loadId'),
    field: 'load_id',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.carrier'),
    field: 'trsa_carrdesc',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.tanker'),
    field: 'trsa_tanker',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.operatorName'),
    field: 'trsa_per_name',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.operator'),
    field: 'trsa_operdesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.startDate'),
    field: 'trsa_st_dmy',
    cellRenderer: 'DateRenderer',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.endDate'),
    field: 'trsa_ed_dmy',
    cellRenderer: 'DateRenderer',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.terminalCode'),
    field: 'trsa_terminal',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.terminal'),
    field: 'trsa_sitedesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.lastModifiedByCode'),
    field: 'trsa_psn',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.lastModifiedBy'),
    field: 'trsa_userdesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
  },
  {
    headerName: t('fields.lastModified'),
    field: 'trsa_crt_dmy',
    cellRenderer: 'DateRenderer',
    sortable: true,
    resizable: true,
  },
];

export default columns;
