const columns = (t, config) => [
  {
    headerName: t('fields.allocIndex'),
    field: 'alloc_index',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: !config?.siteAllowMultiAllocations,
  },
  {
    headerName: t('fields.allocType'),
    field: 'alloc_type',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocTypeName'),
    field: 'alloc_typename',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocTypeDesc'),
    field: 'alloc_typedesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
  },
  {
    headerName: t('fields.allocCmpyCode'),
    field: 'alloc_cmpycode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocCmpyName'),
    field: 'alloc_cmpyname',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocCmpyDesc'),
    field: 'alloc_cmpydesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
  },
  {
    headerName: t('fields.allocSuppCode'),
    field: 'alloc_suppcode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocSuppName'),
    field: 'alloc_suppname',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocSuppDesc'),
    field: 'alloc_suppdesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
  },
  {
    headerName: t('fields.allocLock'),
    field: 'alloc_lock',
    // filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocLockName'),
    field: 'alloc_lockname',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocLockDesc'),
    field: 'alloc_lockdesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
  },
  {
    headerName: t('fields.allocPeriod'),
    field: 'alloc_period',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocPeriodName'),
    field: 'alloc_periodname',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
  },
  {
    headerName: t('fields.allocPeriodDesc'),
    field: 'alloc_perioddesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
  },

  {
    headerName: t('fields.allocStartDate'),
    field: 'alloc_start_date',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    hide: !config?.siteAllocResetPeriodDateRanges,
  },
  {
    headerName: t('fields.allocEndDate'),
    field: 'alloc_end_date',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    hide: !config?.siteAllocResetPeriodDateRanges,
  },
  {
    headerName: t('fields.allocNextDate'),
    field: 'alloc_next_date',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    hide: !config?.siteAllocResetPeriodDateRanges,
  },

  {
    headerName: t('fields.allocDatetime'),
    field: 'alloc_datetime',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
  },
];

export default columns;
