const columns = (t, config) => [
  {
    headerName: t('fields.allocIndex'),
    field: 'alloc_index',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: !config?.siteAllowMultiAllocations,
    width: 80,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocType'),
    field: 'alloc_type',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocTypeName'),
    field: 'alloc_typename',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocTypeDesc'),
    field: 'alloc_typedesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 180,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocCmpycode'),
    field: 'alloc_cmpycode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocCmpyName'),
    field: 'alloc_cmpyname',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocCmpyDesc'),
    field: 'alloc_cmpydesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 320,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocBaseFlag'),
    field: 'alloc_baseflag',
    sortable: true,
    resizable: true,
    cellRenderer: 'BooleanRenderer',
    filter: 'BooleanFilter',
    width: 160,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocSuppcode'),
    field: 'alloc_suppcode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    cellRenderer: 'SupplierRender',
    cellRendererParams: {
      t: t,
      typeColumn: 'alloc_type',
      typeValue: ['1', '3'],
      supplierColumn: 'alloc_suppcode',
      ownerColumn: 'alloc_ownercode',
    },
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocSuppName'),
    field: 'alloc_suppname',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    cellRenderer: 'SupplierRender',
    cellRendererParams: {
      t: t,
      typeColumn: 'alloc_type',
      typeValue: ['1', '3'],
      supplierColumn: 'alloc_suppname',
      ownerColumn: 'alloc_ownername',
    },
    width: 200,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocSuppDesc'),
    field: 'alloc_suppdesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    cellRenderer: 'SupplierRender',
    cellRendererParams: {
      t: t,
      typeColumn: 'alloc_type',
      typeValue: ['1', '3'],
      supplierColumn: 'alloc_suppdesc',
      ownerColumn: 'alloc_ownerdesc',
    },
    width: 320,
    suppressSizeToFit: true,
  },
  /* {
    headerName: t('fields.allocOwnerCode'),
    field: 'alloc_ownercode',
    filter: 'FuzzyFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocOwnerName'),
    field: 'alloc_ownername',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocOwnerDesc'),
    field: 'alloc_ownerdesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: !config?.siteSupplierExchangeAllocation,
    width: 200,
    suppressSizeToFit: true,
  }, */
  {
    headerName: t('fields.allocLock'),
    field: 'alloc_lock',
    // filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocLockName'),
    field: 'alloc_lockname',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocLockDesc'),
    field: 'alloc_lockdesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 150,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocPeriod'),
    field: 'alloc_period',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocPeriodName'),
    field: 'alloc_periodname',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: true,
    width: 140,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocPeriodDesc'),
    field: 'alloc_perioddesc',
    filter: 'MultiFilter',
    sortable: true,
    resizable: true,
    hide: false,
    width: 150,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.allocStartDate'),
    field: 'alloc_start_date',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    hide: !config?.siteAllocResetPeriodDateRanges,
    width: 180,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocEndDate'),
    field: 'alloc_end_date',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    hide: !config?.siteAllocResetPeriodDateRanges,
    width: 180,
    suppressSizeToFit: true,
  },
  {
    headerName: t('fields.allocNextDate'),
    field: 'alloc_next_date',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    hide: !config?.siteAllocResetPeriodDateRanges,
    width: 180,
    suppressSizeToFit: true,
  },

  {
    headerName: t('fields.allocDatetime'),
    field: 'alloc_datetime',
    sortable: true,
    resizable: true,
    cellRenderer: 'DateRenderer',
    width: 180,
    suppressSizeToFit: true,
  },
];

export default columns;
