const columns = (t, config) => [
  {
    headerName: t('fields.terminal'),
    field: 'tank_site',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: true,
    suppressSizeToFit: true,
    width: 120,
  },
  {
    headerName: t('fields.terminal'),
    field: 'tank_sitename',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    hide: !config?.siteUseMultiTerminals,
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: t('fields.baseProductCode'),
    field: 'base_code',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: t('fields.baseProductName'),
    field: 'base_name',
    sortable: true,
    resizable: true,
    filter: 'FuzzyFilter',
    suppressSizeToFit: true,
    width: 180,
  },
  {
    headerName: t('fields.bookBalance'),
    field: 'bookbalance',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 160,
  },
  {
    headerName: t(config?.siteLabelUser + 'fields.grossVolume'),
    field: 'grossvol',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 250,
  },
  {
    headerName: t(config?.siteLabelUser + 'fields.netVolume'),
    field: 'netvol',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 240,
  },
  {
    headerName: t('fields.ullage'),
    field: 'ullage',
    sortable: true,
    resizable: true,
    hide: !config?.siteUllageCalcAuto,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 150,
  },
  {
    headerName: t('fields.usableVolume'),
    field: 'usablevol',
    sortable: true,
    resizable: true,
    cellRenderer: 'SeperatorRenderer',
    cellRendererParams: {
      type: String(config?.decimal_thousand_separator),
    },
    suppressSizeToFit: true,
    width: 170,
  },
];

export default columns;
